/* The English dictionary.
 *
 * A data file, like the `dati-*.js` catalogues: loaded as a `<script>` before
 * `i18n.js`, which takes it into memory at start-up. From then on every
 * `t(key)` is a `Map` read — switching language costs no request and no work.
 *
 * Why not `en.json`: this application also opens with a double-click on
 * `index.html`, and from `file://` a `fetch('en.json')` is forbidden by the
 * browser — the language would never arrive. The contents are a flat
 * key→text object all the same, that is JSON with one header line.
 *
 * A missing key here is not a broken interface: the manager falls back to the
 * Italian source text and reports the key once in the console. That is the
 * whole point of keys — an untranslated string is visible and countable,
 * instead of being silently half-translated by a glossary.
 */

window.ASTRO_DIZIONARI = window.ASTRO_DIZIONARI || {};
window.ASTRO_DIZIONARI['en'] = {
  locale: 'en-GB',
  nome: 'English',
  manifest: 'manifest-en.json',
  messaggi: {
    // --- Il nucleo, il tempo e i punti cardinali ---------------------
    'lingua.cambio': 'Switch to {lingua}',
    'app.titolo': 'Ben\'s AstroCalendar',
    'tempo.adesso': 'now',
    'tempo.passato': 'past',
    'tempo.istanti': 'in a moment',
    'tempo.fra': 'in {durata}',
    'tempo.fa': '{durata} ago',
    'tempo.fraSecondi': { uno: 'in {n} second', altri: 'in {n} seconds' },
    'tempo.breveSecondi': 'in {n} s',
    'tempo.breveMinuti': 'in {n} min',
    'tempo.breveOre': 'in {n} h',
    'tempo.fraMinuti': { uno: 'in {n} minute', altri: 'in {n} minutes' },
    'tempo.fraMinutiSecondi': 'in {n} min {s} s',
    'tempo.fraOre': { uno: 'in an hour', altri: 'in {n} hours' },
    'tempo.fraOreMinuti': 'in {n} h {m} min',
    'tempo.fraGiorni': { uno: 'in {n} day', altri: 'in {n} days' },
    'tempo.fraMesi': { uno: 'in {n} month', altri: 'in {n} months' },
    'tempo.fraAnni': { uno: 'in a year', altri: 'in {n} years' },
    'tempo.fraAnniMesi': { uno: 'in {n} years and a month', altri: 'in {n} years and {m} months' },
    'tempo.unitaGiorni': '{n} d',
    'tempo.unitaOre': '{n} h',
    'tempo.unitaMinuti': '{n} min',
    'tempo.unitaSecondi': '{n} s',
    'tempo.inCorsoOAppenaPassata': 'under way or just past',
    'punto.sigla.n': 'N',
    'punto.sigla.nne': 'NNE',
    'punto.sigla.ne': 'NE',
    'punto.sigla.ene': 'ENE',
    'punto.sigla.e': 'E',
    'punto.sigla.ese': 'ESE',
    'punto.sigla.se': 'SE',
    'punto.sigla.sse': 'SSE',
    'punto.sigla.s': 'S',
    'punto.sigla.ssw': 'SSW',
    'punto.sigla.sw': 'SW',
    'punto.sigla.wsw': 'WSW',
    'punto.sigla.w': 'W',
    'punto.sigla.wnw': 'WNW',
    'punto.sigla.nw': 'NW',
    'punto.sigla.nnw': 'NNW',
    'punto.nome.n': 'north',
    'punto.nome.ne': 'north-east',
    'punto.nome.e': 'east',
    'punto.nome.se': 'south-east',
    'punto.nome.s': 'south',
    'punto.nome.sw': 'south-west',
    'punto.nome.w': 'west',
    'punto.nome.nw': 'north-west',

    // --- Il tempo, e i capolinea ---------------------------------------
    'tempo.capolinea': 'The time machine runs from {da} to {a}.',

    // --- La scheda di un astro (skyRigheScheda) ------------------------
    'scheda.tipo': 'Type',
    'scheda.fase': 'Phase',
    'scheda.discoIlluminato': 'disc {n}% lit',
    'scheda.magnitudine': 'Magnitude',
    'scheda.illuminazione': 'Illumination',
    'scheda.alSole': 'in sunlight, so it can shine',
    'scheda.nellOmbraDellaTerra': 'inside the Earth\'s shadow, invisible',
    'scheda.direzione': 'Direction',
    'scheda.direzioneAzimut': '{punto} (azimuth {az}°)',
    'scheda.altezza': 'Altitude',
    'scheda.sopraOrizzonte': '{gradi}° above the horizon',
    'scheda.sottoOrizzonte': '{gradi}° below the horizon',
    'scheda.daQui': 'From here',
    'scheda.circumpolare': 'it is circumpolar: it never sets',
    'scheda.nonSorgeMai': 'it never rises above the horizon at this latitude',
    'scheda.sorgeTramonta': 'Rises and sets',
    'scheda.codiceCatalogo': 'Catalogue code',
    'scheda.costellazione': 'Constellation',
    'scheda.distanzaTerra': 'Distance from Earth',
    'scheda.dimensioni': 'Size',
    'scheda.temperatura': 'Temperature',
    'scheda.kelvinInSuperficie': 'about {k} K at the surface',
    'scheda.ilSoleNeHa': 'the Sun\'s is 5,800',
    'scheda.indiceColore': 'Colour index',
    'scheda.bv': 'B−V {v}',
    'scheda.bvSpiegazione': 'how much brighter it is in blue than in yellow',
    'scheda.distanzaSole': 'Distance from the Sun',
    'scheda.unitaAstronomiche': '{n} astronomical units',
    'scheda.laLuceCiMette': 'light takes {tempo}',
    'scheda.distanzaSoleInCielo': 'Distance from the Sun in the sky',
    'scheda.troppoVicinoAlSole': 'too close: it sits in the twilight glow',
    'scheda.orbita': 'Orbit',
    'scheda.unGiroOgniMinuti': 'one trip round the Earth every {n} minutes',
    'scheda.coordinate': 'Coordinates',
    'scheda.arDec': 'RA {ar} · Dec {dec}',
    'scheda.epocaDiOggi': 'today\'s epoch',
    'scheda.rispettoEclittica': 'Relative to the ecliptic',
    'scheda.sullaLinea': 'practically on the line',
    'scheda.gradiSopra': '{gradi}° above',
    'scheda.gradiSotto': '{gradi}° below',
    'scheda.longitudine': 'longitude {n}°',
    'scheda.passaPiuAlto': 'Highest point',
    'scheda.aGradiDiAltezza': ', at {gradi}° altitude',

    // --- Le categorie degli eventi e gli strumenti ---------------------
    'categoria.luna': 'Moon phases',
    'categoria.eclissi': 'Eclipses',
    'categoria.stagioni': 'Seasons',
    'categoria.meteore': 'Meteor showers',
    'categoria.pianeti': 'Planets',
    'categoria.congiunzioni': 'Conjunctions',
    'categoria.aurore': 'Auroras',
    'categoria.personali': 'Personal',
    'strumento.occhio': 'With the naked eye',
    'strumento.binocolo': 'With binoculars',
    'strumento.telescopio': 'With a telescope',
    'filtro.tutti': 'All',
    'filtro.tutto': 'Everything',
    'filtro.tutteLeCategorie': 'All categories together',
    'filtro.mostraStrumento.tutti': 'Show what is visible in any case',
    'filtro.mostraStrumento.occhio': 'Show what is visible with the naked eye',
    'filtro.mostraStrumento.binocolo': 'Show what is visible with binoculars',
    'filtro.mostraStrumento.telescopio': 'Show what is visible with a telescope',

    // --- La scheda di un aereo e lo stato del feed ADS-B ---------------
    'aereo.volo': 'Flight',
    'aereo.registrazione': 'Registration',
    'aereo.aeromobile': 'Aircraft',
    'aereo.operatore': 'Operator',
    'aereo.quota': 'Altitude',
    'aereo.velocita': 'Speed',
    'aereo.rotta': 'Heading',
    'aereo.distanza': 'Distance',
    'aereo.inVista': 'In view',
    'aereo.itinerario': 'Route',
    'aereo.icao': 'ICAO code',
    'aereo.squawk': 'Squawk',
    'aereo.finoAAltezza': ', up to {gradi}° altitude',
    'aereo.ancoraPoiTramonta': '{quanto} more{alto}, then it sets',
    'aereo.almeno': 'at least {quanto}{alto}',
    'aereo.posizioneStimata': 'Position estimated from the heading, speed and climb rate of the last ADS-B reading.',
    'aereo.posizioneAllineata': 'Position aligned to the live ADS-B feed.',
    'aereo.ricercaInCorso': 'searching…',
    'aereo.tracciaSullaMappa': 'Real track on the map',
    'aereiStato.quanti': { uno: '1 aircraft', altri: '{n} aircraft' },
    'aereiStato.nuovoScarico': ' · next fetch {quando}',
    'aereiStato.senzaPosizione': 'A location is needed to look for aircraft.',
    'aereiStato.proxyMancante': 'No data: the ADS-B networks do not allow requests from browsers, and right now not one public CORS bridge is answering either. For a route that does not depend on third-party services, configure your own proxy (ADSB_PROXY_URL, see ADSB-PROXY.md).',
    'aereiStato.spento': 'Data paused: switch on “ADS-B data” to fetch nearby traffic.',
    'aereiStato.spentoConDati': 'Data paused · last reading {eta} ({quanti}).',
    'aereiStato.carico': 'First ADS-B fetch under way…',
    'aereiStato.caricoConDati': 'Refreshing… · meanwhile {quanti} from the last reading {eta}.',
    'aereiStato.passato': 'Time machine: {quanti} at positions estimated from the last ADS-B reading. Return to Now for live data.',
    'aereiStato.senzaRete': 'Offline: the ADS-B data will arrive as soon as the connection is back.',
    'aereiStato.senzaReteConDati': 'Offline · the last reading from {eta} remains ({quanti}).',
    'aereiStato.riprovo': ' Retrying {quando}.',
    'aereiStato.errore': 'ADS-B data unavailable ({guaio}).{riprova}',
    'aereiStato.erroreConDati': 'Refresh failed ({guaio}): the last reading from {eta} remains ({quanti}).{riprova}',
    'aereiStato.vecchio': '{quanti} · last reading {eta}: positions propagated from the heading.{prossimo}',
    'aereiStato.primoScarico': 'Waiting for the first ADS-B fetch…',
    'aereiStato.normale': '{quanti} · {fonte} · updated {eta}{prossimo}',

    // --- Il fumetto dell'aereo e i suoi comandi ------------------------
    'aereo.nonComunicata': 'not reported',
    'aereo.partenza': 'From',
    'aereo.destinazione': 'To',
    'aereo.aereo': 'Aircraft',
    'aereo.metriSlm': '{n} m above sea level',
    'aereo.distanzaReale': 'Actual distance',
    'aereo.apriPannello': '{nota}. Open the ADS-B aircraft panel',
    'aereo.nonRiuscito': 'Failed',
    'aereo.aggiornato': 'Updated ✓',
    'aereo.aggiornamento': 'Updating…',
    'aereo.cartaServeRete': 'The map needs a network connection the first time.',
    'aereo.tracciaAdsbDi': 'ADS-B track of {volo}',
    'aereo.nonDisponibile': 'unavailable',

    // --- La scheda di una stella e del cielo profondo ------------------
    'profondo.volteLunaPiena': '{n} times the full Moon',
    'profondo.comeLunaPiena': 'as large as the full Moon',
    'profondo.terzoLunaPiena': 'a third of the full Moon',
    'stella.classe': '{colore} star',
    'stella.classeDedotta': 'roughly class {classe}, inferred from the colour',
    'stella.colore.O': 'Blue',
    'stella.colore.B': 'Blue',
    'stella.colore.A': 'Blue-white',
    'stella.colore.F': 'White',
    'stella.colore.G': 'Yellow',
    'stella.colore.K': 'Orange',
    'stella.colore.M': 'Red',
    'stella.piuCalda': 'hotter than the Sun',
    'stella.piuFredda': 'cooler than the Sun',
    'stella.quasiComeIlSole': 'almost as hot as the Sun',
    'stella.notaColore': 'The colour is not decoration: it tells you the temperature. This one is {colore}, around {gradi} degrees at the surface — {confronto}, whose is 5,800.',
    'stella.notaGigante': 'A red star this visible to the naked eye is almost certainly a giant: red dwarfs are the majority of stars in the Galaxy, but not one is visible without a telescope.',
    'stella.notaAzzurra': 'Blue stars burn fast and live briefly: a few tens of millions of years, against the Sun’s ten billion.',
    'lune.transito': '{luna} is passing in front of Jupiter',
    'lune.ombra': '{luna}’s shadow is on Jupiter’s disc',
    'lune.occultata': '{luna} is hidden behind Jupiter',
    'lune.eclissata': '{luna} is in Jupiter’s shadow cone',
    'lune.tutteNascoste': 'all four hidden by Jupiter',
    'meteo.nonAncoraDisponibili': 'Forecast not available yet.',

    // --- Il racconto della curva dell'altezza --------------------------
    'curva.servePosizione': 'A location is needed to know when it rises.',
    'curva.soloDiGiorno': 'Tonight it never gets above the horizon while the sky is dark: it is up during the day.',
    'curva.nonSorgeMai': 'Tonight it never rises from here.',
    'curva.quasiTuttaLaNotte': 'for almost the whole night',
    'curva.circaOre': 'for about {n} hours',
    'curva.pocoPiuDiUnOra': 'for a little over an hour',
    'curva.menoDiUnOra': 'for less than an hour',
    'curva.momentoBuono': 'The best moment is around {ora}, at {gradi}° above the horizon. Usable {quanto}.',

    // --- Il tasto dei filtri -------------------------------------------
    'ui.filtri': 'Filters',
    'ui.mostraFiltri': 'Show the category and instrument filters',
    'ui.nascondiFiltri': 'Hide the filters',

    // --- La dashboard di Stasera e le Impostazioni ---------------------
    'ui.apri-la-mappa-a-tutto-schermo': 'Open the map full screen',
    'stasera.vedilaNelPlanetario': 'See it in the planetarium',
    'stasera.servePosizione': 'A location is needed to know what is overhead.',
    'stasera.dimmiDoveSono': 'Find where I am',
    'stasera.nienteAbbastanzaAlto': 'Nothing rises high enough from here tonight.',
    'stasera.aprilNelPlanetario': 'Open it in the planetarium, with the map aimed at it',
    'stasera.puntiSu100': '{n} out of 100',
    'stasera.versoLeAGradi': 'around {ora}, at {gradi}°',
    'bersaglio.pianeta': 'planet',
    'bersaglio.cometa': 'comet',
    'bersaglio.asteroide': 'asteroid',
    'cielo.bortleTitolo': 'Bortle {b}: you can see down to magnitude {mag}',
    'cielo.scalaBortle': 'Bortle scale {b}: with the naked eye you reach magnitude {mag}',
    'cielo.cioeStelle': ', that is about {n} stars in the whole sky.',
    'raggi.spenti': 'off',
    'raggi.stoCercando': 'searching…',
    'raggi.nonRiuscito': 'the search failed',
    'raggi.apriIlPlanetario': 'open the planetarium to search',
    'raggi.nienteQuiAttorno': 'nothing nearby',
    'raggi.inVista': ' · {n} in view',

    // --- Il meteo, gli ostacoli e i raggi di ricerca -------------------
    'meteo.nonRiescoAGiudicare': 'I cannot judge the coming nights.',
    'meteo.stoScaricando': 'Downloading the forecast…',
    'meteo.finestraMigliore': 'Best window: {testo}.',
    'orizzonte.altezzaOstacoli': 'Height of the obstacles towards {dove}, in degrees',
    'raggi.senzaMappa': 'The map did not load (it needs the network the first time). The radii can be set with the slider below.',
    'raggi.senzaPosizione': 'I do not know where you are yet: choose a location and the map will appear. Meanwhile the radii can be set with the slider.',
    'raggi.anelloTratteggiato': ' Within {km} km {dentro}; beyond that, {fuori} — that is the dashed ring.',
    'raggi.notaAccesi': 'Mountains, towns and water come from OpenStreetMap; aircraft are updated live via ADS-B.',
    'raggi.notaSpenti': 'Mountain names are off: the horizon stays the shape of the terrain, with no labels. They can also be switched on from the planetarium’s Display panel.',

    // --- I motivi di un bersaglio e il giudizio della notte ------------
    'motivo.restaBasso': 'stays low, only reaches {gradi}°',
    'motivo.nonSaleMolto': 'does not rise much ({gradi}°)',
    'motivo.saleFinoA': 'rises to {gradi}°',
    'motivo.mezzOra': 'just over half an hour of usable window',
    'motivo.finestraStretta': 'narrow window, about {n} hours',
    'motivo.serveIlTelescopio': 'a telescope is needed',
    'motivo.magnitudine': 'magnitude {mag}',
    'motivo.quasiImpossibile': 'from your sky it is almost impossible',
    'notte.lunaSottoOrizzonte': 'Moon below the horizon: the sky at its best',
    'notte.lunaAlPerCento': 'Moon {perc}% lit and {gradi}° above the horizon',
    'notte.sereno': 'clear sky',
    'notte.aTratti': 'patchy cloud',
    'notte.moltoNuvoloso': 'very cloudy',
    'notte.coperto': 'overcast',
    'notte.senzaLuna': 'with no Moon',
    'notte.lunaSchiarisce': 'with the Moon brightening everything',
    'notte.unPoDiLuna': 'with a little Moon',
    'notte.daUnCielo': 'from a «{cielo}» sky',

    // --- La barra del terreno, l'atlante e la scheda della posizione ---
    'terreno.stoMisurando': 'Measuring {che}… {per}%',
    'terreno.pronto': 'The terrain around you is ready.',
    'terreno.ilTerreno': 'the terrain',
    'terreno.elencoFinale': '{prime} and {ultima}',
    'terreno.fase.quote': 'the shape of the terrain',
    'terreno.fase.citta': 'the town lights',
    'terreno.fase.cime': 'the mountain names',
    'terreno.fase.acque': 'the lakes and rivers',
    'terreno.fase.rilievo': 'the terrain relief',
    'atlante.filtro.tutte': 'All',
    'atlante.filtro.australi': 'Southern sky',
    'atlante.filtro.boreali': 'Northern sky',
    'atlante.filtro.disegni': 'With artwork',
    'atlante.filtro.qui': 'Visible from here',
    'atlante.filtro.buio': 'Of the dark',
    'posizione.diRipiego': 'This is a fallback position: it is fine for timings, but if the town is not the right one, pick your city below.',
    'posizione.sceltaDaTe': 'The app is calculating everything from here. You chose it, so it stays: neither GPS nor the network will change it on their own until you press “Detect again”.',
    'posizione.calcoloDaQui': 'The app is calculating everything from here.',
    'sol.senzaLibreria': 'Without the calculation library the planets cannot be placed.',

    // --- I sei quadri della lezione dell'eclittica ---------------------
    'lezione.alto.breve': 'From above',
    'lezione.alto.titolo': 'From above it looks like a target',
    'lezione.alto.testo': 'Seen from over the Sun’s head the Solar System looks like a target: near-perfect circles, all travelled in the same direction, as though someone had drawn them with a compass. It is the picture we all carry in our heads — and it is also the one that hides the most important fact, because seen from above, something flat and something thick look identical.',
    'lezione.taglio.breve': 'Edge-on',
    'lezione.taglio.titolo': 'Turned edge-on: it is not a ball, it is a disc',
    'lezione.taglio.testo': 'Now the same scene drops until we see it in profile, and the circles flatten onto one another. Here is the fact: the planets are not scattered in every direction around the Sun, they all sit inside a thin plate. Each travels on a slightly different plane, but “slightly” means a few degrees.',
    'lezione.piano.breve': 'The plane',
    'lezione.piano.titolo': 'The floor of the Solar System',
    'lezione.piano.testo': 'To measure those degrees you need a floor to count them from, and the choice is natural: the plane of the Earth’s orbit, that is, ours. Extend it to infinity, out to the stars: the circle it traces in the sky is <strong>the ecliptic</strong>. The other orbits cross it barely tilted — Mercury 7.0°, Venus 3.4°, Saturn 2.5°, Mars 1.8°, Jupiter 1.3° — and that is why they always stay close to it.',
    'lezione.daQui.breve': 'From here',
    'lezione.daQui.titolo': 'How we see it from inside',
    'lezione.daQui.testo': 'We sit inside that floor and look at it edge-on: that is why the Sun, the Moon and the planets seem strung along the same line, crossing the sky from one horizon to the other. It is exactly the line the planetarium’s “Ecliptic” button switches on. These are the real planets of right now: the vertical scale is stretched six times, otherwise those two or three degrees would not show.',
    'lezione.analemma.breve': 'The analemma',
    'lezione.analemma.titolo': 'The ecliptic watched always at the same hour',
    'lezione.analemma.testo': 'Try going out every day at the same hour and marking where the Sun is. You do not get a point — nor a line: you get a <strong>stretched figure of eight</strong>, the analemma. The two causes are the same as before, taken one at a time. The Earth’s axis is tilted by 23.4°, and this raises and lowers the Sun by 47° between the two solstices: that is the height of the eight. The orbit is an ellipse, so in winter the Earth runs faster and the Sun reaches noon early or late by up to a quarter of an hour: that is the width. On the map you will find it switched on together with the ecliptic, in pale gold, and it passes exactly through where the Sun is right now.',
    'lezione.nome.breve': 'The name',
    'lezione.nome.titolo': 'Why it is called the “ecliptic”',
    'lezione.nome.testo': 'The name comes from eclipses. The Moon orbits on a plane tilted 5° to ours, so it touches the ecliptic at just two points: the <strong>nodes</strong>. For an eclipse you need two coincidences at once — the Moon at a node, and the Sun in the same direction (solar eclipse) or the opposite one (lunar eclipse). Watch the Sun go round: only twice a year does it line up with the nodes, and that is when the eclipse seasons open. That is why we do not get one a month. The tilt of the lunar orbit here is drawn four times stronger than the real thing: at exactly 5° it would be indistinguishable from the thickness of the line.',

    // --- Le fasi lunari ------------------------------------------------
    'fase.0.titolo': 'New Moon',
    'fase.0.spiegazione': 'The Moon sits between the Earth and the Sun. The face turned towards us is in shadow: a dark sky, excellent for deep-sky observing.',
    'fase.0.cosaPortare': 'A telescope for galaxies and nebulae, since the sky is very dark.',
    'fase.0.doveVederlo': 'Go far from the city to make the most of the total darkness.',
    'fase.0.comeVederlo': 'Use a star map to find your way in the dark.',
    'fase.1.titolo': 'First Quarter Moon',
    'fase.1.spiegazione': 'Half the lunar disc is lit. This is the best time to observe the craters along the terminator, where the shadows are long and sharp.',
    'fase.1.cosaPortare': 'Binoculars or a small telescope for the craters.',
    'fase.1.doveVederlo': 'Visible in the evening, high in the sky after sunset.',
    'fase.1.comeVederlo': 'Look at the light/shadow boundary: that is where the detail stands out.',
    'fase.2.titolo': 'Full Moon',
    'fase.2.spiegazione': 'The Earth sits between the Sun and the Moon. The lunar disc is fully lit and brilliant.',
    'fase.2.cosaPortare': 'Binoculars for the lunar seas; a moon filter helps against the intense light.',
    'fase.2.doveVederlo': 'Anywhere the sky is clear towards the horizon.',
    'fase.2.comeVederlo': 'To the naked eye the light is intense: a moon filter makes observing more comfortable.',
    'fase.3.titolo': 'Last Quarter Moon',
    'fase.3.spiegazione': 'The other half of the lunar disc is lit. It rises deep in the night and is visible in the early morning.',
    'fase.3.cosaPortare': 'Binoculars or a telescope; an early alarm for dawn.',
    'fase.3.doveVederlo': 'In the morning sky, before dawn.',
    'fase.3.comeVederlo': 'Make the most of the dark sky in the second half of the night for deep sky.',

    // --- The Solar System bodies, and the two lines of their card ------
    //     One name for the whole application: the sky, the object list,
    //     the agenda cards, the 3D view and the ecliptic lesson all read
    //     these ten entries (see `nomeCorpo` in app.js).
    'corpo.Sun': 'Sun',
    'corpo.Moon': 'Moon',
    'corpo.Mercury': 'Mercury',
    'corpo.Venus': 'Venus',
    'corpo.Earth': 'Earth',
    'corpo.Mars': 'Mars',
    'corpo.Jupiter': 'Jupiter',
    'corpo.Saturn': 'Saturn',
    'corpo.Uranus': 'Uranus',
    'corpo.Neptune': 'Neptune',
    'corpo.Sun.classe': 'A star: ours',
    'corpo.Sun.nota': 'It holds 99.86% of the mass of the whole Solar System.',
    'corpo.Moon.classe': 'Natural satellite of the Earth',
    'corpo.Moon.nota': 'It always shows us the same face: it turns on itself in exactly the time it takes to go round us.',
    'corpo.Mercury.classe': 'Rocky planet',
    'corpo.Mercury.nota': 'It never strays far from the Sun: you only catch it in the twilight, very low down.',
    'corpo.Venus.classe': 'Rocky planet',
    'corpo.Venus.nota': 'The brightest object after the Sun and the Moon: its sulphuric-acid clouds reflect 70% of the light.',
    'corpo.Mars.classe': 'Rocky planet',
    'corpo.Mars.nota': 'The orange colour is iron oxide: rust, on a planetary scale.',
    'corpo.Jupiter.classe': 'Gas giant',
    'corpo.Jupiter.nota': 'Hold a pair of binoculars steady and you can see the four satellites Galileo found.',
    'corpo.Saturn.classe': 'Gas giant',
    'corpo.Saturn.nota': 'The rings show in even a small telescope: they are ice, a few tens of metres thick.',
    'corpo.Uranus.classe': 'Ice giant',
    'corpo.Uranus.nota': 'At the very limit of the naked eye under a very dark sky: in binoculars it is a greenish dot.',
    'corpo.Neptune.classe': 'Ice giant',
    'corpo.Neptune.nota': 'Never visible to the naked eye: it was found by calculation before it was found by telescope.',

    // --- Lunar eclipses ------------------------------------------------
    'eclissiLunare.titolo': '{tipo} Lunar Eclipse',
    'eclissiLunare.tipo.penumbral': 'Penumbral',
    'eclissiLunare.tipo.partial': 'Partial',
    'eclissiLunare.tipo.total': 'Total',
    'eclissiLunare.spiegazione': 'The Earth casts its shadow on the Moon, darkening it and — during a total eclipse — turning it a reddish colour (the “Blood Moon”).',
    'eclissiLunare.cosaPortare': 'Open eyes and, if you like, a camera with a telephoto lens.',
    'eclissiLunare.doveVederlo': 'Anywhere the Moon is above the horizon.',
    'eclissiLunare.comeVederlo': 'Just look at it with the naked eye, no filter of any kind needed.',

    // --- Solar eclipses ------------------------------------------------
    'eclissiSolare.titolo': '{tipo} Solar Eclipse',
    'eclissiSolare.tipo.partial': 'Partial',
    'eclissiSolare.tipo.annular': 'Annular',
    'eclissiSolare.tipo.total': 'Total',
    'eclissiSolare.tipo.hybrid': 'Hybrid',
    'eclissiSolare.tipoInFrase.partial': 'a partial one',
    'eclissiSolare.tipoInFrase.annular': 'an annular one',
    'eclissiSolare.tipoInFrase.total': 'a total one',
    'eclissiSolare.tipoInFrase.hybrid': 'a hybrid one',
    'eclissiSolare.fase.total': 'totality',
    'eclissiSolare.fase.annular': 'annularity',
    'eclissiSolare.fase.centrale': 'central phase',
    'eclissiSolare.oscurato': 'At maximum the Sun is about {n}% obscured.',
    'eclissiSolare.spiegazioneConFascia': 'The Moon passes in front of the Sun ({tipo}). The point of greatest eclipse — where the eclipse is deepest and {fase} lasts longest — lies at {coord}, at the centre of the narrow track that crosses the Earth.',
    'eclissiSolare.spiegazioneAttorno': 'All around it, for a few thousand kilometres, the eclipse is seen as partial.',
    'eclissiSolare.spiegazioneParziale': 'The Moon covers only part of the Sun\'s disc (a globally partial eclipse): the axis of the shadow misses the Earth\'s surface, so there is no point of totality.',
    'eclissiSolare.spiegazioneParzialeDove': 'It can be watched as a partial eclipse, mostly from the polar regions or from the areas under the Moon\'s penumbra.',
    'eclissiSolare.doveConFascia': 'Point of greatest eclipse: {coord}. {fase} is visible only along the narrow track through that point; the partial phase is visible over a wide region (up to a few thousand km) all around the track. Check whether your area falls inside it.',
    'eclissiSolare.doveParziale': 'No track of totality: the eclipse is partial wherever it is visible, usually towards the polar regions. Check whether your area falls inside the visibility zone.',
    'eclissiSolare.sullaMappa': 'Point of greatest eclipse on the map ({coord})',
    'eclissiSolare.cosaPortare': 'MANDATORY: certified eclipse glasses (ISO 12312-2) or a solar filter. Never look at the Sun with the naked eye, not even when it is partly eclipsed.',
    'eclissiSolare.comeVederlo': 'Use certified solar filters only, or pinhole projection. Never binoculars or a telescope without a proper solar filter.',

    // --- Equinoxes and solstices ---------------------------------------
    'stagione.primavera.titolo': 'Spring Equinox',
    'stagione.primavera.spiegazione': 'The Sun crosses the celestial equator: day and night are almost the same length. Spring begins in the northern hemisphere.',
    'stagione.estate.titolo': 'Summer Solstice',
    'stagione.estate.spiegazione': 'The longest day of the year in the northern hemisphere: the Sun reaches its greatest height at noon.',
    'stagione.autunno.titolo': 'Autumn Equinox',
    'stagione.autunno.spiegazione': 'Day and night are nearly equal again: autumn begins in the northern hemisphere.',
    'stagione.inverno.titolo': 'Winter Solstice',
    'stagione.inverno.spiegazione': 'The longest night of the year in the northern hemisphere: the Sun is at its lowest above the horizon.',
    'stagione.riga.cosaPortare': 'Nothing in particular: this is a date on the astronomical calendar.',
    'stagione.riga.doveVederlo': 'There is no one spot to “see”: it marks the turn of the season.',
    'stagione.riga.comeVederlo': 'Notice how sunrise and sunset times shift over the following days.',

    // --- Meteor showers ------------------------------------------------
    //     The names are dictionary entries and not proper nouns: the
    //     Italian «Quadrantidi» are the Quadrantids here.
    'sciame.titolo': 'Meteor shower: {nome}',
    'sciame.nome.quadrantidi': 'Quadrantids',
    'sciame.nome.liridi': 'Lyrids',
    'sciame.nome.etaAquaridi': 'Eta Aquariids',
    'sciame.nome.deltaAquaridi': 'Southern Delta Aquariids and Alpha Capricornids',
    'sciame.nome.perseidi': 'Perseids',
    'sciame.nome.orionidi': 'Orionids',
    'sciame.nome.leonidi': 'Leonids',
    'sciame.nome.geminidi': 'Geminids',
    'sciame.nome.ursidi': 'Ursids',
    'sciame.spiegazioneFino': 'A shower of falling stars (up to {n} meteors an hour in the best conditions). The meteors seem to radiate from a single point on the sky.',
    'sciame.spiegazioneCirca': 'A shower of falling stars (around {n} meteors an hour in the best conditions). The meteors seem to radiate from a single point on the sky.',
    'sciame.riga.cosaPortare': 'A deck chair, a blanket and something hot to drink. No telescope: what you need is a wide field of view.',
    'sciame.riga.doveVederlo': 'A dark sky with no light pollution; give your eyes 20 minutes to adapt.',
    'sciame.riga.comeVederlo': 'Look up with the naked eye, after midnight, when the radiant is higher.',
    'sciame.deltaAquaridi.spiegazione': 'A double shower peaking on the night of 30–31 July. The Southern Delta Aquariids give medium-speed trails (up to about 25 meteors an hour in perfect conditions), while the Alpha Capricornids produce very bright, slow fireballs.',
    'sciame.deltaAquaridi.cosaPortare': 'A deck chair, a blanket and something to drink. No telescope: what you need is a wide field of view.',
    'sciame.deltaAquaridi.doveVederlo': 'Away from city lights, somewhere with a clear horizon; give your eyes 20 minutes to adapt to the dark.',
    'sciame.deltaAquaridi.comeVederlo': 'With the naked eye, looking up; the best time is around 3 a.m., when the radiant is highest in the sky.',

    // --- Greatest elongation of Mercury and Venus ----------------------
    'elongazione.titolo': 'Greatest Elongation of {corpo}',
    'elongazione.spiegazione': '{corpo} reaches its greatest apparent distance from the Sun ({gradi}°): this is the best time to look for it, visible {quando}.',
    'elongazione.alMattino': 'in the morning, before dawn',
    'elongazione.allaSera': 'in the evening, after sunset',
    'elongazione.cosaPortare': 'Binoculars; a small telescope to make out its phase.',
    'elongazione.doveVederlo': 'Towards the {verso} horizon, {quando}.',
    'elongazione.comeVederlo': 'Find a horizon clear of obstacles: the planet stays low down.',

    // --- Conjunctions and occultations ---------------------------------
    'congiunzione.titolo': '{a}–{b} conjunction',
    'congiunzione.titoloOccultazione': 'Occultation: {a} hides {b}',
    'congiunzione.primiDArco': '{n} arcminutes (less than a degree: they fit together in the field of a pair of binoculars)',
    'congiunzione.spiegazione': '{a} and {b} close to within {distanza}. They do not really touch — they stay enormously far apart — but from the Earth they look almost superimposed: it is one of the easiest sights to recognise, even from town.',
    'congiunzione.spiegazioneOccultazione': '{a} and {b} come within {distanza} of each other: from some parts of the Earth the Moon passes in front of the planet and hides it for a few tens of minutes. From elsewhere you still get a spectacular close approach. Check the local times below.',
    'congiunzione.cosaPortare': 'Nothing compulsory: it shows to the naked eye. Binoculars put them together in one field, and a phone takes good pictures of it.',
    'congiunzione.doveVederlo': 'You need a clear horizon in the right direction: look at the “from here” panel below to find out where and when they are visible from your place.',
    'congiunzione.comeVederlo': 'Look for the two bright points very close together: the one that does not twinkle is the planet — stars flicker.',

    // --- Supermoons and micromoons -------------------------------------
    'luna.super.titolo': 'Supermoon',
    'luna.super.spiegazione': 'Full Moon at {km} km, near the closest point of its orbit. The disc measures {primi} arcminutes, {percento}% larger than average.',
    'luna.super.programma': 'The difference is real but modest: 14% between the largest and the smallest of the year, and with nothing in the sky to compare it against the eye cannot tell. The way to really see it is to photograph it always with the same lens and compare the shots months apart. The “huge Moon” you see on the horizon, on the other hand, has nothing to do with distance: it is an optical illusion — on the horizon the Moon is in fact slightly farther away than at the zenith.',
    'luna.micro.titolo': 'Micromoon',
    'luna.micro.spiegazione': 'Full Moon at {km} km, near the farthest point of its orbit: the smallest disc of the year, {primi} arcminutes.',
    'luna.micro.programma': 'The smallest and faintest full Moon of the year. It is not a spectacle: it is the yardstick you need in order to notice, six months later, how much it changes.',

    // --- Oppositions and solar conjunctions ----------------------------
    'opposizione.titolo': '{corpo} at opposition',
    'opposizione.spiegazione': '{corpo} is on the opposite side of the sky from the Sun: it rises at sunset, is highest at midnight and sets at dawn. It is {ua} astronomical units from the Earth and shines at magnitude {mag}: this is the best night of the year to look at it.',
    'opposizione.programma.Mars': 'This is the only spell when Mars shows anything at all: away from an opposition it stays an orange dot even in large telescopes. Wait until it is high, let the instrument cool down, and push the magnification much further than seems reasonable.',
    'opposizione.programma.Saturn': 'The rings are the thing that converts people to astronomy. Fifty times magnification is enough to see them clear of the disc.',
    'opposizione.programma.Jupiter': 'The two dark belts show even in a small refractor, and the four moons change their arrangement from hour to hour: look at the start and at the end of the evening.',
    'opposizione.programma.lontani': 'You need a chart to pick it out among the stars: at a careless glance it is just another faint star. The sure way is to look two evenings running and see which one has moved.',
    'congiunzioneSole.titolo': '{corpo} in conjunction with the Sun',
    'congiunzioneSole.spiegazione': '{corpo} passes behind the Sun as seen from here: for a few weeks either side it cannot be observed.',
    'congiunzioneSole.programma': 'There is nothing to look at, and that is exactly the point: if you were looking for it and could not find it, this is why. It will come back in the morning sky, low in the east before dawn.',

    // --- Venus at greatest brilliancy ----------------------------------
    'splendore.titolo': '{corpo} at greatest brilliancy',
    'splendore.spiegazione': '{corpo} reaches magnitude {mag}, the brightest of this apparition. Only {n}% of it is lit — a crescent — but it is so close that the crescent more than makes up for it.',
    'splendore.programma': 'At this brightness {corpo} casts a shadow: from a dark spot, with the Moon below the horizon, hold a sheet of white paper in front of you and look. In binoculars, held very steady, the crescent already shows — and it is the same observation that in 1610 convinced Galileo that Venus goes round the Sun and not round us.',

    // --- Transits across the Sun's disc --------------------------------
    'transitoSole.titolo': 'Transit of {corpo} across the Sun',
    'transitoSole.spiegazione': '{corpo} passes in front of the Sun\'s disc: a perfectly round black dot crossing it in {ore} hours, from {da} to {a}. At mid-transit it passes {primi} arcminutes from the centre of the Sun.',
    'transitoSole.avvisoFiltro': '⚠ NEVER look at the Sun without a certified solar filter fitted IN FRONT of the objective: one second is enough to blind you for life, and through a telescope the damage is instant and painless. Filters that screw into the eyepiece must never be used — they crack from the heat. Otherwise, projection onto a sheet of white card is safe and shows everything.',
    'transitoSole.nota.Venus': 'Transits of Venus come in pairs eight years apart, and then none for over a century: miss one and you do not get another.',
    'transitoSole.nota.Mercury': 'Mercury\'s dot is tiny, a hundred and sixtieth of the Sun\'s diameter: you need real magnification — a filter over your glasses is not enough.',

    // --- Comets --------------------------------------------------------
    'cometa.titolo': 'Comet {nome} at its brightest',
    'cometa.spiegazione': 'Comet {nome} reaches magnitude {mag}, at {ua} astronomical units from the Earth and {uaSole} from the Sun.',
    'cometa.finestraSettimane': { uno: 'It stays within reach for about a week.', altri: 'It stays within reach for about {n} weeks.' },
    'cometa.finestraCorta': 'The window is only a few days.',
    'cometa.aOcchio': 'It should show to the naked eye from a dark spot, but do not expect the photograph: to the eye a comet is a fuzzy patch with perhaps a hint of a tail. Binoculars are the right instrument, better than a telescope — you need a wide field, not magnification.',
    'cometa.alBinocolo': 'Look for it with binoculars: comets are big and faint, and a telescope magnifies too much to hold them.',
    'cometa.avvertenza': 'Bear in mind that brightness forecasts for comets are often badly wrong, in both directions: it depends on how much ice evaporates, and that is only found out when it happens.',

    // --- Polar aurorae -------------------------------------------------
    'aurora.boreale': 'borealis',
    'aurora.australe': 'australis',
    'aurora.previsione.titolo': 'Aurora {dove}: Kp {kp} forecast',
    'aurora.previsione.apertura': 'NOAA forecasts a Kp index of {kp} for tonight. From here — {gradi}° geomagnetic latitude —',
    'aurora.previsione.addosso': 'the auroral oval comes down over your head: if the sky is clear the green arcs show high up to the {verso}, and with a storm this size they can reach the zenith.',
    'aurora.previsione.solaCoda': 'the oval stays beyond the horizon, but not all of it: the green lives at 100–180 km and the curvature of the Earth hides it, while the oxygen red at two hundred kilometres and more still peeks over. Expect a pinkish glow low to the {verso}, not green arcs — it is the aurora that was seen from Italy in May 2024.',
    'aurora.previsione.alLimite': 'it is marginal: you need a {verso} horizon that is completely clear and dark.',
    'aurora.previsione.incertezza': 'Three-day Kp forecasts are often a point out, either way.',
    'aurora.previsione.cosaPortare': 'No instruments: an aurora is tens of degrees wide and binoculars cut it up. A camera on a tripod, if anything — the sensor sees the colours that the eye, in the dark, can barely tell apart.',
    'aurora.previsione.doveVederlo': 'Somewhere with the {verso} horizon completely clear and no lit-up town on that side: an orange dome of light wipes out a red glow. The coast, a ridge, an open field.',
    'aurora.previsione.comeVederlo': 'Give your eyes twenty minutes before judging, and keep watching: an aurora changes within minutes and substorms arrive in waves, with half an hour of nothing in between. The best moment is around magnetic midnight, that is shortly before or after true midnight. The «See in the planetarium» button shows you the shape it would have from here right now.',
    'aurora.stagione.titolo.marzo': 'Aurora season — the March equinox',
    'aurora.stagione.titolo.settembre': 'Aurora season — the September equinox',
    'aurora.stagione.spiegazione': 'Around the equinoxes geomagnetic storms are about twice as frequent as around the solstices, and it is no coincidence: it is the Russell-McPherron effect. The magnetic field the Sun blows at us arrives wound in a spiral, and in March and September the tilt of the Earth\'s axis presents it to the Earth\'s field in the direction that favours reconnection — which is the tap the energy of an aurora comes through. The three weeks around this date are the time of year when it is worth keeping an eye on the forecasts.',
    'aurora.stagione.daQui': 'From here, at {gradi}° geomagnetic latitude,',
    'aurora.stagione.bastaKp': 'a Kp of {kp} is enough for something to show to the {verso}: in a good season that happens several times.',
    'aurora.stagione.servirebbeKp': 'you would need a Kp of {kp}: that happens a few times per solar cycle, and May 2024 was the last one.',
    'aurora.stagione.fuoriScala': 'it would take an off-the-scale storm — from your latitude an aurora is a once-in-many-decades thing.',
    'aurora.stagione.cosaPortare': 'Nothing special: an aurora is watched with the naked eye. What does help is a phone with geomagnetic storm alerts, because the real warning is only a few hours.',
    'aurora.stagione.doveVederlo': 'You need a {verso} horizon that is clear and dark. If you live on a plain, pick the right spot once and go back to it: when the storm comes there is no time to go looking.',
    'aurora.stagione.doveVederloSenzaCasa': 'You need a clear, dark horizon towards the nearer pole.',
    'aurora.stagione.comeVederlo': 'This is not a fixed-date event and nobody can promise it: it is a season. The «Your sky tonight» panel on the dashboard shows the forecast Kp for the next three nights, and that is the moment to decide whether to go out. The «Polar aurorae» bench in the Learn view explains where all this comes from, and takes you into the planetarium at a place and on a night when the aurora really was seen.',

    // --- The observability index, and what the sky is like --------------
    'osserva.nonAlPicco': 'not at the moment of the peak, but around {ora}',
    'osserva.sottoOrizzonte': 'not visible from here: below the horizon',
    'osserva.basso': 'low on the horizon ({gradi}°)',
    'osserva.cieloChiaro': 'sky still bright at that hour',
    'osserva.nuvole': '{come} ({n}% cloud)',
    'osserva.senzaPrevisione': 'no weather forecast available',
    'osserva.lunaAlta': 'Moon {n}% lit and high in the sky: it brightens the background',
    'nuvole.senzaPrevisione': 'no forecast available',
    'nuvole.sereno': 'clear sky',
    'nuvole.pocoNuvoloso': 'slightly cloudy',
    'nuvole.aTratti': 'cloudy at times',
    'nuvole.moltoNuvoloso': 'very cloudy',
    'nuvole.coperto': 'overcast',
    'meteo.caricoPrevisioni': 'Loading the forecast…',
    'meteo.senzaRete': 'Forecast unavailable (it needs the network). Everything else is computed locally and still holds.',
    'meteo.nessunaPerStanotte': 'No forecast for the hours of tonight.',
    'meteo.mediaStanotte': '({n}% cloud on average tonight)',
    'meteo.oraMigliore': 'Best hour: {ora} with {n}%',
    'meteo.previsioneDi': 'forecast from {quanto}',

    // --- The frame of the agenda and of the month grid ------------------
    'agenda.nessunEvento': 'No events to show.',
    'agenda.nessunEventoNelMese': 'No events in {mese} {anno} with the current filters. Try another month, another search or another category.',
    'agenda.nessunEventoTrovato': 'No event matches the search. Try other words, or another category.',
    'agenda.manuale': 'Manual',
    'agenda.modifica': 'Edit',
    'agenda.modificaTitolo': 'Edit event',
    'agenda.elimina': 'Delete',
    'agenda.eliminaTitolo': 'Delete event',
    'foto.etichetta.obiettivo': 'Lens',
    'foto.etichetta.esposizione': 'Exposure',
    'foto.etichetta.errore': 'Mistake to avoid',
    'calendario.oggi': 'Today',

    // --- The «Tonight» panel of the dashboard ---------------------------
    'stanotte.mancaPosizione': 'Your position is missing',
    'stanotte.mancaPosizioneTesto': 'Without a point on the Earth I cannot tell you when it gets dark, what rises and what sets. There are three ways to give it to me — GPS, your connection, or your town picked from a list — and at least one always works. It is stored on this device only.',
    'stanotte.buioAstronomico': 'Astronomical darkness',
    'stanotte.nienteBuio': 'no full darkness tonight',
    'stanotte.tramontoAlba': 'Sunset {tramonto} · sunrise {alba}',
    'stanotte.crepuscoloTuttaNotte': 'The Sun never gets down to \u221218°: twilight all night long. Sunset {tramonto}.',
    'stanotte.nonCalcolabile': 'cannot be worked out',
    'stanotte.latitudiniAlte': 'At your latitude the Sun may not set at all.',
    'stanotte.lunaOrari': 'Rises {sorge} · sets {tramonta}.',
    'stanotte.disturbo.alto': 'sky much brighter: better the Moon and the planets than faint objects',
    'stanotte.disturbo.medio': 'moderate interference for faint objects',
    'stanotte.disturbo.basso': 'dark sky: excellent for meteors and deep sky',
    'stanotte.datiNonDisponibili': 'data unavailable',
    'stanotte.senzaLibreriaOrbitale': 'Orbital library not loaded: reopen the app while you have a connection, and then it will work offline too.',
    'faseLuna.nuova': 'New Moon',
    'faseLuna.crescente': 'Waxing crescent',
    'faseLuna.primoQuarto': 'First Quarter',
    'faseLuna.gibbosaCrescente': 'Waxing gibbous',
    'faseLuna.piena': 'Full Moon',
    'faseLuna.gibbosaCalante': 'Waning gibbous',
    'faseLuna.ultimoQuarto': 'Last Quarter',
    'faseLuna.calante': 'Waning crescent',

    // --- Il blocco «Da qui» delle schede dell'agenda -------------------
    'locale.servePosizione': 'With your location I can tell you whether this event is visible from your home, at what time and in which direction.',
    'locale.sorgeTramonta': 'Rises {sorge} · sets {tramonta}',
    'locale.buioAstronomico': 'Astronomical darkness that night: {da} → {a}',
    'locale.osservabilita': 'Observability {punti}/100',
    'locale.momentoConsigliato': 'Recommended moment: {quando}',
    'locale.sottoMaRecupera': 'At the peak it is below the horizon from here, but the same night it reaches {gradi}° around {ora}.',
    'locale.nonVisibile': 'Not visible from here: at the moment of the event the object is below the horizon.',
    'locale.cieloAncoraChiaro': 'At the exact time of the event the sky is still bright (Sun at {sole}°)',
    'locale.guardaloVersoLe': ': look for it around {ora}, when it is {gradi}° high towards {dove}.',
    'locale.cercaNelBuio': '. Look for the object in the nearest hours of darkness.',
    'locale.bassaSullOrizzonte': 'Visible but low on the horizon ({gradi}°): you need a clear view towards {dove}.',
    'locale.benVisibile': 'Clearly visible from here: {gradi}° above the horizon, towards {dove}.',

    // --- I consigli di astrofotografia ---------------------------------
    'foto.base.treppiede': 'A tripod (even a small one) makes more difference than any expensive lens.',
    'foto.base.telefono': 'With a phone: Pro or Night mode, a 3-second self-timer so you do not shake it, manual focus at ∞.',
    'foto.luna.titolo': 'Photographing the Moon',
    'foto.luna.obiettivo': 'The longest you have: 200–300 mm on a DSLR, optical zoom on a phone.',
    'foto.luna.esposizione': 'The “looney” rule: 1/125 s, f/8, ISO 100. The Moon is lit by the Sun, so treat it as a daytime subject.',
    'foto.luna.errore': 'The classic mistake is overexposing: if you get a white disc with no craters, cut 2–3 stops.',
    'foto.eclissi.titolo': 'Photographing the eclipse',
    'foto.eclissi.obiettivo': 'A 200 mm telephoto or longer. For a solar eclipse you need a certified solar filter in front of the lens.',
    'foto.eclissi.esposizione': 'Lunar eclipse: ISO 800, f/5.6, 1/4 s during totality (the red Moon is far darker). Partial solar eclipse: like a daytime photo, but only with a filter.',
    'foto.eclissi.errore': 'Never point at the Sun without a filter: you will burn the sensor and, if you look through the viewfinder, your eye too.',
    'foto.meteore.titolo': 'Photographing shooting stars',
    'foto.meteore.obiettivo': 'A fast wide-angle (14–24 mm, f/2.8 or faster): you need field, not magnification.',
    'foto.meteore.esposizione': 'ISO 1600–3200, f/2.8, 15–20 s frames back to back for hours. The 500 rule: maximum seconds = 500 ÷ focal length; beyond that the stars become dashes.',
    'foto.meteore.errore': 'You do not chase the meteor: you aim the camera at a patch of sky ~40° from the radiant and shoot continuously.',
    'foto.pianeti.titolo': 'Photographing planets and conjunctions',
    'foto.pianeti.obiettivo': 'For a conjunction a 50–100 mm is enough: what makes the picture is the landscape with the two bodies close together.',
    'foto.pianeti.esposizione': 'ISO 400–800, f/4, 1–2 s if they are still in twilight. Planets are bright: better to underexpose.',
    'foto.pianeti.errore': 'Include a tree or a roofline: a photo of two dots in the black tells no story.',
    'foto.cielo.titolo': 'Photographing the sky',
    'foto.cielo.obiettivo': 'A fast wide-angle and manual focus on a bright star.',
    'foto.cielo.esposizione': 'ISO 1600, f/2.8, 10–20 s. Shoot RAW if you can: you recover a lot in post.',
    'foto.cielo.errore': 'Avoid digital zoom: it ruins the detail without adding anything.',

    // --- Lo stato del planetario, la bussola e la barra del tempo ------
    'fonte.gps.breve': 'GPS',
    'fonte.gps.provenienza': 'detected by the device\'s GPS',
    'fonte.rete.breve': 'network',
    'fonte.rete.provenienza': 'inferred from your connection',
    'fonte.citta.breve': 'chosen town',
    'fonte.citta.provenienza': 'the town you chose',
    'fonte.manuale.breve': 'by hand',
    'fonte.manuale.provenienza': 'the coordinates you typed',
    'fonte.salvata.breve': 'saved',
    'fonte.salvata.provenienza': 'the last saved position',
    'fonte.backup.breve': 'from backup',
    'fonte.backup.provenienza': 'restored from a backup',
    'stato.cieloVistoDa': 'Sky seen from {dove} — this applies to the planetarium only, the app position does not change',
    'stato.posizione': 'Position: {dove}',
    'stato.posizioneNonRilevata': 'Position not detected yet',
    'bussola.nessunSensore': 'Compass: no sensor (move the view with your finger)',
    'bussola.intestazione': 'Compass: {fonte}',
    'bussola.fonte.quaternione': 'full attitude from the system (no degenerate pose)',
    'bussola.fonte.evento': 'browser orientation angles',
    'bussola.fonte.ponte': 'gyroscope locked to magnetic north',
    'bussola.fonte.attesa': 'waiting for a reading',
    'bussola.tarataSu': 'calibrated on {astro} ({gradi}°)',
    'bussola.correzioneManuale': 'manual correction {gradi}°',
    'bussola.declinazione': 'magnetic declination {gradi}°',
    'bussola.inaffidabile': 'the phone reports it as unreliable',
    'bussola.disturbata': 'disturbed by about {gradi}°',
    'bussola.dettoAVoce': 'View towards {dove}, {gradi} degrees, field of view {campo}',
    'bussola.modo.astro': 'Compass calibrated on the real sky: north is exact by construction',
    'bussola.modo.vera': 'Compass: the amber tip is geographic north',
    'bussola.modo.dubbia': 'Compass disturbed by something made of iron: calibrate it on a star',
    'bussola.modo.magnetica': 'Compass needs calibrating: the north shown is magnetic north',
    'bussola.modo.manuale': 'You move the view with your finger: north is that of the drawn sky',
    'schermo.entra': 'Sky full screen',
    'schermo.esci': 'Leave full screen',
    'barraTempo.aVoce': 'Device time {luogo}; {direzione}, {scarto}',
    'barraTempo.aVoceDueFusi': 'Local time {luogo}; current device time {dispositivo}; {direzione}, {scarto}',
    'barraTempo.titolo': '{esteso} · device {dispositivo}{scarto} — tap for the date and the time step',
    'barraTempo.tempoReale': ' (real time)',
    'registra.fermaTitolo': 'Stop recording here and keep what you have captured',
    'registra.titoloCielo': 'Record {n} seconds of sky to share',
    'registra.titoloSolare': 'Record {n} seconds of the 3D Solar System to share',
    'registra.ferma': 'Stop recording',
    'registra.cielo': 'Record the sky',
    'registra.solare': 'Record the 3D Solar System',

    // --- La cornice delle schede dell'agenda ---------------------------
    'agenda.tuttiInArrivo': 'You are reading every upcoming event. Pick a month to see that one instead, including in the past.',
    'agenda.simula': 'Simulate',
    'agenda.simulaTitolo': 'Watch what happens, step by step',
    'agenda.ascolta': 'Listen',
    'agenda.ascoltaTitolo': 'Read aloud',
    'agenda.cosaSuccede': 'What happens',
    'agenda.comePrepararsi': 'How to prepare',
    'agenda.portare': 'Bring',
    'agenda.dove': 'Where',
    'agenda.come': 'How',
    'agenda.strumentoConsigliato': 'Recommended instrument',
    'azione.diarioTitolo': 'Record the observation in the logbook',
    'azione.visto': 'Seen!',
    'azione.segnaVisto': 'Mark as seen',
    'azione.condividi': 'Share',
    'azione.condividiTitolo': 'Share the event',
    'azione.cartolina': 'Postcard',
    'azione.cartolinaTitolo': 'Create a postcard to send in a chat',
    'azione.calendario': 'To calendar',
    'azione.calendarioTitolo': 'Add to your phone\'s calendar',

    // --- Le scorciatoie di un evento e le righe del mese ---------------
    'scorciatoia.planetario': 'See in the planetarium',
    'scorciatoia.planetarioTitolo': 'Opens the planetarium at the moment of the event, aimed where to look',
    'scorciatoia.posto': 'Find the best spot',
    'scorciatoia.postoTitolo': 'Looks within the chosen radius for a point where mountains and hills do not block the event',
    'scorciatoia.ombra': 'Shadow map',
    'scorciatoia.ombraTitolo': 'The path of the shadow cone, minute by minute',
    'scorciatoia.doveQuando': 'Where and when to see it',
    'scorciatoia.doveQuandoTitolo': 'Where it is visible from, at what time, and how high the Moon is',
    'scorciatoia.perche': 'Why it happens',
    'scorciatoia.percheTitolo': 'The Earth and the Moon seen from outside at that instant, to true scale, with their shadow cones: why the alignment works that evening',
    'mese.eventiDi': 'Events in {mese} {anno}, calculated for this month.',
    'mese.staiLeggendo': 'You are reading {mese} {anno}. Use “All upcoming” to return to the events ahead.',
    'mese.calcoloInCorso': 'Calculating the events for {mese} {anno}…',

    // --- Lo schermo intero del planetario ------------------------------
    'schermo.esciTitolo': 'Leave full screen (also with Esc)',

    // --- Le unita' della barra del tempo e i nomi dei passi ------------
    'barraTempo.unitaAnni': '{n} y',
    'barraTempo.unitaGiorni': '{n} d',
    'barraTempo.unitaOre': '{n} h',
    'barraTempo.unitaMinuti': '{n} m',
    'barraTempo.unitaSecondi': '{n} s',
    'barraTempo.futuro': 'Future',
    'barraTempo.passato': 'Past',
    'barraTempo.tempoReale': 'Real time',
    'passo.reale': 'Real time',
    'passo.s10': '10 s',
    'passo.min1': '1 min',
    'passo.min10': '10 min',
    'passo.h1': '1 h',
    'passo.g1': '1 d',
    'passo.mese1': '1 month',
    'passo.anno1': '1 year',
    'passo.alSecondo': '{passo}/s',

    // --- L'interfaccia statica di index.html -------------------------
    'ui.a-occhio-nudo': 'With the naked eye',
    'ui.a-tutto-schermo': 'Full screen',
    'ui.accendi-l-ovale-aurorale-boreale-o-australe': 'Switch on the auroral oval — northern or southern, depending on the hemisphere — drawn in the sky where it really is: whether you can see it from here, and how much of it rises above the horizon, is decided by the curvature of the Earth. Switching it on reveals the storm slider below, and the line that tells you what would be visible from here',
    'ui.aerei': 'Aircraft',
    'ui.aerei-leggenda-rotte': '<span class="aereo-leggenda itinerario"></span> great-circle route · <span class="aereo-leggenda osservata"></span> real ADS-B track · <span class="aereo-leggenda prevista"></span> 5-minute forecast',
    'ui.agenda': 'Agenda',
    'ui.aggiorna': 'Refresh',
    'ui.aggiorna-adesso': 'Refresh now',
    'ui.aggiornamento-automatico': 'Automatic refresh',
    'ui.aggiunge-le-nuvole-previste-per-questo-luogo': 'Adds the cloud cover forecast for this place and hour to the atmosphere',
    'ui.aggiungi-evento': 'Add event',
    'ui.aggiungi-un-evento-tuo': 'Add an event of your own',
    'ui.aiuti-disegnati-sopra-al-cielo': 'Guides drawn over the sky',
    'ui.all-oculare': 'At the eyepiece',
    'ui.allineamento-delle-stelle-in-corso': 'Aligning the stars…',
    'ui.allineamento-puntamento-e-scaletta-per-il': 'Alignment, aiming and observing plan for your telescope',
    'ui.anno-si-puo-scrivere-fino-al-3000': 'Year: you can type it, up to 3000',
    'ui.annulla': 'Cancel',
    'ui.apre-il-planetario-sullo-stesso-momento-con': 'Opens the planetarium at the same moment, with the Sun eclipsed in the sky',
    'ui.apri-il-pannello-degli-aerei-ads-b': 'Open the ADS-B aircraft panel',
    'ui.apri-la-scheda-quando-il-mirino-giallo-resta': 'Open the card when the yellow crosshair rests on an object.',
    'ui.apri-questo-punto-in-google-maps': 'Open this point in Google Maps',
    'ui.astri': 'Objects',
    'ui.astri-dietro-i-monti': 'Objects behind hills',
    'ui.astrocalendario-di-ben': 'Ben’s AstroCalendar',
    'ui.atlante-costellazioni': 'Constellation atlas',
    'ui.atlante-delle-costellazioni': 'Constellation atlas',
    'ui.atmosfera': 'Atmosphere',
    'ui.aurora': 'Aurora',
    'ui.avanti': 'Next',
    'ui.avanti-di-un-passo': 'Forward one step',
    'ui.avvia-il-filmato-dell-ombra': 'Start the shadow animation',
    'ui.avvia-il-playback': 'Start playback',
    'ui.avvisami': 'Notify me',
    'ui.avvisami-prima-di-un-evento': 'Notify me before an event',
    'ui.azzera': 'Reset',
    'ui.backup-e-ripristino': 'Backup and restore',
    'ui.basta-la-citta-piu-vicina-per-gli-orari-del': 'The nearest town is enough: for sky timings a few kilometres change nothing.',
    'ui.butta-questo-e-registra-di-nuovo': 'Discard this and record again',
    'ui.calcola-gli-eventi': 'Calculate the events',
    'ui.calcolo-in-corso': 'Calculating…',
    'ui.calibra': 'Calibrate',
    'ui.cambia-oculare': 'Change eyepiece:',
    'ui.campo-55': '55° field',
    'ui.caricamento-dei-dati-orbitali': 'Loading orbital data…',
    'ui.caricamento-del-planetario': 'Loading the planetarium',
    'ui.carta-geografica-della-rotta-dellaereo': 'Map of the aircraft’s route',
    'ui.categoria': 'Category',
    'ui.centra': 'Centre',
    'ui.cerca-il-luogo-per-nome': 'Search for the place by name',
    'ui.cerca-nel-sistema-solare': 'Search the Solar System',
    'ui.cerca-per-nome': 'Search by name…',
    'ui.cerca-un-aereo': 'Search for an aircraft',
    'ui.cerca-un-astro-per-nome': 'Search for an object by name',
    'ui.cerca-un-elemento-nel-sistema-solare': 'Search for a body in the Solar System',
    'ui.cerca-una-citta': 'Search for a town',
    'ui.cerca-una-citta-o-un-paese': 'Search for a town or village',
    'ui.cerca-una-costellazione': 'Search for a constellation',
    'ui.che-cielo-avrai': 'Your sky conditions',
    'ui.che-cos-e-l-eclittica': 'What the ecliptic is',
    'ui.che-cosa-cercare': 'What to look for',
    'ui.che-cosa-regolare': 'What to adjust',
    'ui.che-mappa-mostrare': 'Which map to show',
    'ui.chi-muove-la-vista': 'What moves the view',
    'ui.chiede-al-dispositivo-la-posizione-attuale-e': 'Asks the device for your current position and brings the point here',
    'ui.chiede-il-permesso-al-browser-all-aperto-e': 'Asks the browser for permission. Outdoors this is the best route.',
    'ui.chiedi-adesso-una-nuova-fotografia-senza': 'Request a new snapshot now, without waiting for the next round',
    'ui.chiudi': 'Close',
    'ui.chiudi-i-comandi-del-tempo': 'Close the time controls',
    'ui.chiudi-il-pannello-ads-b': 'Close the ADS-B panel',
    'ui.chiudi-l-avviso-del-transito': 'Dismiss the transit alert',
    'ui.chiudi-la-finestra': 'Close the window',
    'ui.chiudi-la-finestra-o-premi-esc': 'Close the window (or press Esc)',
    'ui.chiudi-la-galleria': 'Close the gallery',
    'ui.chiudi-la-mappa': 'Close the map',
    'ui.chiudi-la-mappa-e-torna-al-planetario': 'Close the map and return to the planetarium',
    'ui.chiudi-la-scheda': 'Close the card',
    'ui.chiudi-la-simulazione': 'Close the simulation',
    'ui.cielo': 'Sky',
    'ui.cielo-limpido-vista-da-con-il-binocolo-ho': 'Clear sky, seen from… with binoculars. I noticed that…',
    'ui.circa-la-citta': 'roughly the town',
    'ui.citta': 'Towns',
    'ui.citta-e-montagne': 'Towns and mountains',
    'ui.citta-e-montagne-trovate': 'Towns and mountains found',
    'ui.citta-trovate': 'Towns found',
    'ui.colore': 'Colour',
    'ui.com-e-andata': 'How did it go?',
    'ui.comandi-del-planetario': 'Planetarium controls',
    'ui.come-e-disegnato': 'How it is drawn',
    'ui.come-guardare-il-cielo-e-cosa-disegnarci': 'How to look at the sky and what to draw on it: direction, display, objects, air, landscape',
    'ui.come-guardare-pieno-schermo-colori-notturni': 'How to look: full screen, night colours, camera, grid',
    'ui.come-guardarla-senza-farsi-male': 'How to watch it safely',
    'ui.come-si-legge-la-mappa': 'How to read the map',
    'ui.come-si-leggono-i-colori': 'How to read the colours',
    'ui.come-si-presenta-davvero-non-come-nelle': 'How it really looks, not how it looks in photographs',
    'ui.come-vederlo': 'How to see it',
    'ui.comete-e-asteroidi': 'Comets and asteroids',
    'ui.comete-e-asteroidi-abbastanza-luminosi-da': 'Comets and asteroids bright enough to be seen tonight: almost always there are none, and when there is one it is the reason to go out',
    'ui.compresse': 'Compressed',
    'ui.compresse-per-farceli-stare-tutti-gli-angoli': 'Compressed so they all fit: the angles stay true, the ratios between distances do not',
    'ui.computer-doppio-clic-sul-terreno-telefono-un': 'Computer: double-click on the terrain · phone: one tap · then choose “Go here” · two fingers to zoom · the blue marker is where you really are',
    'ui.con-bussola-e-giroscopio-accesi-il-cielo-lo': 'With the compass and gyroscope on, the phone aims the sky. Switch it off and you move the map with your finger, and the Centre button and cardinal points work again',
    'ui.con-cosa-guardi': 'What are you observing with?',
    'ui.con-il-binocolo': 'With binoculars',
    'ui.con-il-telescopio': 'With a telescope',
    'ui.con-la-fotocamera': 'With a camera',
    'ui.condividi': 'Share',
    'ui.confronta-terreno-e-strade-attorno-a-te-e': 'Compares the terrain and roads around you and looks for a public spot, reachable by car, with the event clear of mountains and hills.',
    'ui.conosco-le-coordinate-esatte': 'I know the exact coordinates',
    'ui.conserva-il-centro-e-l-elevazione-scelti': 'Keeps the centre and elevation you chose; rotates the camera and adapts only the zoom',
    'ui.controllo-del-tempo': 'Time control',
    'ui.corpi-ingranditi-pallini-leggibili-e-comodi': 'Enlarged bodies: dots that are readable and easy to tap. In the Earth and Moon bench it enlarges the shadows too, so the geometry stays that of two bodies three times larger.',
    'ui.cosa-aspettarsi': 'What to expect',
    'ui.cosa-disegnare-sulla-mappa-pianeti-stelle': 'What to draw on the map: planets, stars, satellites, aircraft',
    'ui.cosa-guardare': 'What to observe',
    'ui.cosa-hai-davanti': 'What lies ahead of you',
    'ui.cosa-portare': 'What to bring',
    'ui.cosa-si-vede-stanotte-da-casa-tua': 'What is visible tonight from your home',
    'ui.cosa-succede': 'What happens',
    'ui.cosa-succede-nel-cielo-all-istante-che-stai': 'What is happening in the sky at the moment you are looking at: eclipses, meteor showers, moon phases, conjunctions',
    'ui.cosa-succede-nel-cielo-intorno-all-ora': 'What happens in the sky around the hour shown, and the schedule for the seven days after. Move the clock and the list moves with it.',
    'ui.cosa-vedrai-minuto-per-minuto': 'What you will see, minute by minute',
    'ui.costellazioni': 'Constellations',
    'ui.crea-astrocalben': 'Create “astrocalben”',
    'ui.da-0-5-a-10-secondi-il-conto-riparte-se-il': 'From 0.5 to 10 seconds. The count restarts if the crosshair leaves the object.',
    'ui.da-dove-guardare-il-cielo': 'Where to watch the sky from',
    'ui.da-dove-guardi': 'Where you are watching from',
    'ui.da-google-maps': 'From Google Maps',
    'ui.da-qui': 'From here',
    'ui.da-qui-la-terra-in-basso-e-il-sole-davanti-a': 'From here: the Earth below and the Sun in front of it, that is tonight’s layout seen from above our home. Evening planets on the left, morning ones on the right.',
    'ui.da-qui-nell-istante-di-massima-eclissi-la': 'From here, at the moment of greatest eclipse, the Moon is above the horizon.',
    'ui.dal': 'From',
    'ui.dalla-connessione': 'From the connection',
    'ui.data-e-ora': 'Date and time *',
    'ui.data-ora-e-playback-del-cielo': 'Date, time and sky playback',
    'ui.dati': 'Data',
    'ui.diario': 'Logbook',
    'ui.diario-di-osservazione': 'Observing logbook',
    'ui.didat-tica': 'Learning­ lab',
    'ui.dimensioni': 'Sizes',
    'ui.direzione': 'Direction',
    'ui.direzione-della-vista': 'Direction of view',
    'ui.disegna-i-triangoli-sopra-il-cielo-colorati': 'Draws the triangles over the sky, coloured by distance. It does not touch the feed: switch it off and the data keeps arriving',
    'ui.disegna-in-cielo-gli-aerei-ads-b-entro-il': 'Draws the ADS-B aircraft within the chosen radius in the sky, coloured by distance',
    'ui.disegni': 'Artwork',
    'ui.distanze': 'Distances',
    'ui.distanze-e-dimensioni-compresse-per-farci': 'Distances and sizes: compressed so everything fits, or the real ones',
    'ui.distanze-vere-nettuno-e-settantasette-volte': 'True distances: Neptune is seventy-seven times farther than Mercury, and it shows',
    'ui.dove-si-guarda-punti-cardinali-campo-visivo': 'Where you are looking: cardinal points, field of view, compass and position',
    'ui.dove-sta-passando-l-ombra': 'Where the shadow is passing',
    'ui.dove-ti-trovi': 'Where you are',
    'ui.dove-vedere-l-evento': 'Where to see the event',
    'ui.dove-vederlo': 'Where to see it',
    'ui.durata-della-registrazione': 'Recording length',
    'ui.e-la-posizione-principale-quella-che-comanda': 'This is the main position, the one that drives the whole app. If you choose it yourself, it stays: GPS and network will not replace it on their own until you ask for a new fix. In the planetarium you can move the viewpoint elsewhere without touching this one.',
    'ui.eclissi-lunare': 'Lunar eclipse',
    'ui.eclittica': 'Ecliptic',
    'ui.esci': '✕ Exit',
    'ui.esci-dal-sistema-solare-e-guardalo-da-fuori': 'Step outside the Solar System and look at it from there: where each planet sits on its orbit at this instant, and in which direction you are looking at it from here. Drag to rotate.',
    'ui.esci-dallo-schermo-intero-anche-con-esc-o-un': 'Leave full screen (also with Esc or a double-click)',
    'ui.esporta-backup': 'Export backup',
    'ui.eventi': 'Events',
    'ui.eventi-in-cielo': 'Events in the sky',
    'ui.eventi-personali-diario-di-osservazione-e': 'Personal events, observing logbook and preferences live only in this browser: save them so you do not lose them.',
    'ui.fai-camminare-il-cielo-da-solo': 'Let the sky run on its own',
    'ui.fai-camminare-il-tempo': 'Let time run',
    'ui.ferma-il-filmato': 'Stop the animation',
    'ui.ferma-il-filmato-dell-ombra': 'Stop the shadow animation',
    'ui.ferma-il-tempo': 'Stop time',
    'ui.ferma-la-simulazione': 'Stop the simulation',
    'ui.filtro-rosso-protegge-la-vista-notturna': 'Red filter: protects your night vision',
    'ui.fine': 'End',
    'ui.fotocamera': 'Camera',
    'ui.galleria': 'Gallery',
    'ui.galleria-video': 'Video gallery',
    'ui.gestisci-la-posizione': 'Manage your position',
    'ui.giorno-del-mese': 'Day of the month',
    'ui.gira-la-vista-dove-succede': 'Turn the view to where it happens',
    'ui.gli-istanti-sono-gli-stessi-per-tutto-il': 'The moments are the same for the whole planet: what changes is only whether, from where you are, the Moon is above the horizon at that time.',
    'ui.gli-oggetti-di-stanotte': 'Tonight’s objects',
    'ui.gli-orari-da-casa-tua': 'The timings, from your home',
    'ui.gps-del-dispositivo': 'Device GPS',
    'ui.gradi-decimali-con-il-punto-sud-e-ovest-si': 'Decimal degrees, with a full stop: south and west are written with a minus (−). On an online map just press and hold on the point to read them.',
    'ui.guarda': 'Look',
    'ui.guarda-il-cielo-da-qui': 'Watch the sky from here',
    'ui.guarda-verso': 'Look towards',
    'ui.guarda-verso-est': 'Look east',
    'ui.guarda-verso-nord': 'Look north',
    'ui.guarda-verso-ovest': 'Look west',
    'ui.guarda-verso-sud': 'Look south',
    'ui.guardalo-da-sotto': 'Look at it from below',
    'ui.ho-visto': 'I saw it!',
    'ui.i-laghi-e-i-fiumi-veri-attorno-a-te': 'The real lakes and rivers around you, drawn where they are and at the distance they are: still water reflects the sky like a mirror, and the Moon lays its path of light across it. Only those not hidden behind a ridge are visible. They are downloaded from OpenStreetMap once and then stay available offline; how far to look for them is set in Settings',
    'ui.i-nomi-delle-montagne-che-spuntano-sopra-l': 'The names of the mountains that rise above the horizon, with their altitude, pinned to the real summit by a thread: only those actually visible from here are named, not the ones hidden behind a nearer ridge. They start switched off; once on they are downloaded once and the choice is remembered. How far to look for them is set in Settings',
    'ui.i-quadri-della-lezione': 'The panels of the lesson',
    'ui.ics-aiuto': 'Download an <code>.ics</code> file with the upcoming events: your phone’s calendar will take care of the reminders, even with the app closed.',
    'ui.il-cerchio-che-il-sole-percorre-in-un-anno': 'The circle the Sun travels through the stars in a year: the plane of the Earth’s orbit seen edge-on. The planets always stay within a few degrees of this line, and the plumb line measures how many. It stays on whichever object you pick, until you switch it off',
    'ui.il-cielo-a-tutto-schermo-con-i-comandi-in': 'The sky full screen, with the controls overlaid',
    'ui.il-cielo-che-hai': 'The sky you have',
    'ui.il-cielo-da-cui-osservi': 'The sky you are observing from',
    'ui.il-cielo-di-stanotte-da-casa-tua': 'Tonight’s sky, from your home',
    'ui.il-cielo-mostrato-non-e-quello-di-adesso': 'The sky shown is not the sky of right now: tap to return to real time',
    'ui.il-cielo-occupa-tutto-lo-schermo-anche-con': 'The sky fills the whole screen (also with a double-click on the map)',
    'ui.il-nord-punta-storto-bussola-e-posizione': 'Is north off? Compass and position',
    'ui.il-palazzo-di-fronte-la-collina-gli-alberi': 'The building opposite, the hill, the trees. Declare how high they are in degrees (a fist at arm’s length is about 10°) and from then on the app stops offering you things you will never see from home. Zero means a clear horizon.',
    'ui.il-percorso-del-cono-d-ombra-sulla-terra': 'The path of the shadow cone across the Earth',
    'ui.il-planetario-e-su-questo-istante': 'The planetarium is at this moment.',
    'ui.il-planetario-punta-il-telefono-verso-il': 'Planetarium: point your phone at the sky and see what is there',
    'ui.il-punto-che-al-massimo-ha-la-luna': 'The point that has the Moon exactly overhead at maximum: from there you look straight up, with nothing in the way.',
    'ui.il-resto-dell-app-dice-cosa-c-e-stanotte-qui': 'The rest of the app tells you what is out tonight. Here is how to frame it: the figures are worked out for your own instrument, the instructions talk about real knobs, and the two hard parts — putting the axis on north and finding the object — you do guided, with the phone’s level, compass and push-to.',
    'ui.il-sistema-solare-a-tutto-schermo-con-la': 'The Solar System full screen, with the time bar overlaid',
    'ui.il-sistema-solare-adesso': 'The Solar System, right now',
    'ui.il-sistema-solare-in-3d': 'The Solar System in 3D',
    'ui.il-sistema-solare-visto-da-fuori-nello': 'The Solar System seen from outside, at the same instant: it opens full screen, aimed at the Earth',
    'ui.il-tempo': 'Time',
    'ui.il-tuo-momento': 'Your moment',
    'ui.il-tuo-sistema-solare': 'Your Solar System',
    'ui.il-tuo-telescopio': 'Your telescope',
    'ui.il-valore-predefinito-e-5-secondi-puoi': 'The default is 5 seconds; you can choose from 1 to 60 seconds.',
    'ui.imposta-la-tua-posizione': 'Set your location',
    'ui.impostazioni': 'Settings',
    'ui.in-attesa-dei-dati-ads-b': 'Waiting for ADS-B data…',
    'ui.incolla': 'Paste',
    'ui.incolla-qui-il-link-di-google-maps-o-le': 'Paste the Google Maps link here, or the coordinates',
    'ui.incolla-un-link-di-google-maps-o-scrivi-le': 'Paste a Google Maps link, or type the coordinates',
    'ui.indietro': 'Back',
    'ui.indietro-di-un-passo': 'Back one step',
    'ui.informazioni-dal-mirino': 'Information from the crosshair',
    'ui.ingrandisci-fino-a-vedere-i-mari-della-luna': 'Zoom in (far enough to see the Moon’s seas and Saturn’s rings)',
    'ui.ingrandite': 'Enlarged',
    'ui.inizio': 'Start',
    'ui.insegui': 'Track',
    'ui.installa-l-app': 'Install the app',
    'ui.installa-l-app-sul-dispositivo': 'Install the app on this device',
    'ui.istante-mostrato-apri-i-comandi-del-tempo': 'Moment shown: open the time controls',
    'ui.kp-vero': 'Real Kp',
    'ui.l-aria-sopra-di-te-colore-del-cielo-nuvole': 'The air above you: sky colour, clouds, aurora',
    'ui.l-ho-vista-scrivilo-nel-diario': 'I saw it: write it in the logbook',
    'ui.l-istante-mostrato-tocca-per-data-e-passo': 'The moment shown: tap for the date and the time step',
    'ui.l-istante-mostrato-tocca-per-scrivere-una': 'The moment shown: tap to type a date',
    'ui.l-orizzonte-attorno-a-te': 'The horizon around you',
    'ui.l-orizzonte-prende-la-forma-vera-del-terreno': 'The horizon takes the real shape of the terrain around you: hills, mountains, sea, plain — each with its own colour. It is downloaded once and then stays available offline. Switched off, the terrain is not drawn. Zoom far enough into an object and the terrain turns transparent by itself, as in Stellarium',
    'ui.la-cartella-di-astrocalendario-non-e-ancora': 'The AstroCalendar folder is not connected yet',
    'ui.la-citta-in-elenco-o-le-coordinate-esatte': 'A town from the list, or the exact coordinates. Works offline and without permissions.',
    'ui.la-classifica-usa-le-strade-e-i-divieti-di': 'The ranking uses the roads and access restrictions present in OpenStreetMap, as well as altitude and terrain profile. The data may be incomplete: before setting off, check signage, whether you can stop, the weather and the safety of the place.',
    'ui.la-forma-vera-del-terreno-non-solo-la-sua': 'The real shape of the terrain, not just its outline: the valleys running down, the flanks of the hills, the cut of the river, drawn in strokes as on a panoramic plate. Around you the step is twenty-seven metres, against the three degrees of the banded profile. It is downloaded once per place (four to six tiles) and then stays available offline. Switched off, the banded profile returns',
    'ui.la-luna-entra-nell-ombra-della-terra-chi-la': 'The Moon enters the Earth’s shadow: everyone who can see it in the sky sees all of it, at the same moment',
    'ui.la-mappa-a-tutto-schermo-con-i-comandi-in': 'The map full screen, with the controls overlaid',
    'ui.la-mappa-non-e-disponibile-adesso-serve-la': 'The map is not available right now — it needs the network to load. The coordinates in the “From Google Maps” panel work all the same.',
    'ui.la-modalita-hover-e-disponibile-quando-la': 'Hover mode is available when the view follows the phone',
    'ui.la-posizione-resta-salvata-solo-su-questo': 'Your position stays saved on this device only: it is not sent to anyone, and the app uses it to do the maths locally.',
    'ui.la-scegli-tu': 'You choose it',
    'ui.la-strada-che-l-oggetto-scelto-percorre-nel': 'The path the chosen object travels across the sky in the hours around this moment: dashed where it has already been, solid where it is going, with the hour marked hour by hour',
    'ui.la-terra-e-la-luna-da-vicino-coi-due-coni-d': 'The Earth and the Moon close up, with their two shadow cones: this is where you see why an eclipse does not happen at every full Moon — the Moon’s orbit is tilted by 5.1°, and at that distance it means thirty-four thousand kilometres off target.',
    'ui.la-terra-sotto-di-te-terreno-rilievo-luci': 'The ground beneath you: terrain, relief, lights, water',
    'ui.la-tua-nota': 'Your note',
    'ui.la-tua-posizione': 'Your location',
    'ui.laboratorio': 'Lab',
    'ui.laboratorio-didattico-e-simulazioni': 'Learning lab and interactive celestial-mechanics simulations',
    'ui.laghi-e-fiumi': 'Lakes and rivers',
    'ui.lascia-solo-gli-astri-che-adesso-stanno': 'Keep only the objects that are above the horizon right now',
    'ui.latitudine': 'Latitude',
    'ui.le-cupole-di-luce-dei-paesi-veri-attorno-a': 'The light domes of the real towns around you, with their names on the horizon: they tell you which way NOT to look for faint things. They are not visible by day',
    'ui.le-distanze-fra-le-orbite-sono-compresse-per': 'The distances between the orbits are compressed to fit them all on screen: Saturn really is twenty-five times farther than Mercury. The angles, which are what the lesson is about, are the true ones.',
    'ui.le-eclissi-di-casa-tua': 'Eclipses where you live',
    'ui.le-figure-delle-costellazioni': 'The constellation figures',
    'ui.le-ottantotto-costellazioni-la-figura-il': 'All eighty-eight constellations: the figure, the artwork, the names other cultures gave them, and whether you can see it from here. Half are southern and never rise from Italy: from there, you can travel.',
    'ui.le-registrazioni-salvate-con-astrocalendario': 'Recordings saved with AstroCalendar, available offline too',
    'ui.le-stelle-luminose-di-riferimento': 'The bright reference stars',
    'ui.le-tue-osservazioni': 'Your observations',
    'ui.le-tue-osservazioni-e-i-traguardi-raggiunti': 'Your observations and the milestones you have reached',
    'ui.lenta': 'slow',
    'ui.linea-del-giorno-e-della-notte': 'Day and night line',
    'ui.lo-zoom-con-due-dita-rotellina-o-trackpad': 'Zooming with two fingers, the wheel or the trackpad is always available.',
    'ui.longitudine': 'Longitude',
    'ui.luci-delle-citta': 'Town lights',
    'ui.luna-allo-zenit': 'Moon at the zenith',
    'ui.luogo-incolla-aiuto': 'In Google Maps press and hold on the point: the coordinates appear, and one tap copies them. Long links with <code>@</code> work too, as do degrees and minutes (45°58\'34"N 7°39\'29"E) and two bare numbers. Short <code>maps.app.goo.gl</code> links do not: open one once, and copy what it becomes.',
    'ui.mandalo-con-le-app-del-telefono': 'Send it with your phone’s apps',
    'ui.mappa': 'Map',
    'ui.mappa-a-tutto-schermo': 'Map full screen',
    'ui.mappa-a-tutto-schermo-o-premi-f': 'Map full screen (or press F)',
    'ui.mappa-dei-punti-di-osservazione': 'Map of observing spots',
    'ui.mappa-di-visibilita': 'Visibility map',
    'ui.mappa-sul-computer-fai-doppio-clic-sul': 'Map: on a computer double-click; on a phone tap a point, then choose Go here',
    'ui.massimo': 'Maximum',
    'ui.mese': 'Month',
    'ui.mese-corrente': 'Current month',
    'ui.mini-mappa-di-vai-qua': 'Mini-map for “Go here”',
    'ui.minuto-per-minuto': 'Minute by minute',
    'ui.misure-vere-i-diametri-seguono-la-scala': 'True sizes: the diameters follow the astronomical scale of the zoom; with True distances everything uses the same yardstick. In the Earth and Moon bench the shadows are exact too',
    'ui.modalita-hover': 'Hover mode',
    'ui.modalita-notte': 'Night mode',
    'ui.mostra': 'Show',
    'ui.mostra-anche-cio-che-in-questo-momento-e': 'Also show what is below the horizon at this moment',
    'ui.mostra-gli-astri-anche-quando-si-trovano': 'Show objects even when they are behind the outline of hills and mountains. Switched off, the terrain hides them as it does in reality',
    'ui.mostra-i-pulsanti-e-sulla-mappa': 'Show the + and − buttons on the map',
    'ui.mostra-il-colore-del-cielo-la-foschia-e-gli': 'Shows the sky colour, the haze and the glows. Switching it off also switches off the clouds',
    'ui.mostra-in-cielo': 'Show in the sky',
    'ui.mostra-tutti-i-dati': 'Show all the data',
    'ui.nasconde-tutte-le-informazioni-e-i-comandi': 'Hides all the overlaid information and controls; only the record button remains. Tap the sky to bring them back',
    'ui.nascondi-automaticamente-la-carta-del': 'Hide the route map automatically after this long.',
    'ui.nascondi-la-linea-del-giorno-e-della-notte': 'Hide the day and night line',
    'ui.nel-planetario-puoi-vedere-paesi-acqua': 'In the planetarium you can see towns, water, mountains and aircraft in real time. How far to look for them you decide here, on the map: at the centre is where you watch the sky from, and the four circles are the search radii. Drag the edge of a circle, or tap the point you want to reach; you can also open the map full screen.',
    'ui.nel-raggio': 'within the radius',
    'ui.nessun-astro-con-questo-nome': 'No object by that name.',
    'ui.nomi-astri': 'Object names',
    'ui.nomi-dei-monti': 'Mountain names',
    'ui.non-impostata': 'Not set.',
    'ui.normale': 'normal',
    'ui.nuovo-evento': 'New event',
    'ui.nuvole': 'Clouds',
    'ui.oggetti': 'Objects',
    'ui.ogni-riga-e-un-eclissi-solare-che-da-questo': 'Each row is a solar eclipse that is visible, at least in part, from this point. Tap one to open its map.',
    'ui.oppure-un-intervallo': 'Or a date range',
    'ui.orari-calcolati-per-il-punto-che-hai-scelto': 'Timings calculated for the point you chose. Tap a row to move the time cursor there.',
    'ui.orizzonte-libero': 'Clear horizon',
    'ui.osservazione': 'Observing',
    'ui.paesaggio': 'Landscape',
    'ui.passa-al-fondo-scuro-di-notte-con-gli-occhi': 'Switches to the dark background: at night, with eyes used to the dark, a light map dazzles',
    'ui.passo': 'Step',
    'ui.pausa': 'Pause',
    'ui.perche-il-cielo-fa-quello-che-fa': 'Why the sky does what it does',
    'ui.perche-l-ombra-disegna-una-curva-a-s': 'Why the shadow traces an S-curve',
    'ui.perche-proprio-adesso-la-stagione-delle': 'Why now: the eclipse season',
    'ui.permette-di-correggere-la-bussola': 'Lets you correct the compass by dragging your finger across the sky',
    'ui.pianeti': 'Planets',
    'ui.plane-tario': 'Plane­tarium',
    'ui.planetario': 'Planetarium',
    'ui.porta-al-centro-della-mappa-l-oggetto': 'Bring the selected object to the centre of the map',
    'ui.porta-gli-eventi-nel-tuo-calendario': 'Take the events into your own calendar',
    'ui.porta-il-cielo-alla-data-scritta-qui-accanto': 'Take the sky to the date typed alongside (or press Enter)',
    'ui.porta-il-punto-qui': 'Bring the point here',
    'ui.posizione': 'Location',
    'ui.posizione-attuale': 'Current location',
    'ui.posizioni-ads-b-entro-il-raggio-scelto-50-km': 'ADS-B positions within the chosen radius (50 km by default; change it in Settings). The colour says how close it is; the dashed line is the route for the next 5 minutes. Move the clock and the aircraft and its route become estimates consistent with the moment shown.',
    'ui.precisa-al-metro': 'accurate to the metre',
    'ui.prendi-quello-che-hai-copiato': 'Take what you copied',
    'ui.prepariamo-il-planetario': 'Preparing the planetarium',
    'ui.programma-facoltativo': 'Plan (optional)',
    'ui.prossimi-appuntamenti': 'Coming up',
    'ui.pulisci': 'Clear',
    'ui.punta-il-mirino-su-un-astro-che-vedi-davvero': 'Aim the crosshair at an object you can actually see (the Moon, the Sun, a planet, a bright star) and tap here: the compass corrects itself against the real sky',
    'ui.puoi-scegliere-una-cartella-gia-esistente-e': 'You can choose an existing folder and load its videos straight away, or create a new one.',
    'ui.quando': 'When',
    'ui.quante-stelle-si-vedono-non-dipende-dal': 'How many stars you can see does not depend on the sky but on where you look at it from. Pick the one that most resembles yours: it drives the planetarium (how many stars it draws), the choice of tonight’s targets and the contrast calculation at the telescope.',
    'ui.quanti-minuti-di-eclissi-scorrono-in-un': 'How many minutes of eclipse pass in one second of animation',
    'ui.quanto-manca-alla-forma-vera-del-terreno': 'How far off the real shape of the terrain is',
    'ui.qui-la-luna-resta-su-dal-primo-all-ultimo': 'Here the Moon stays up from first to last contact. The zone is narrower because the Earth turns meanwhile.',
    'ui.raggio-di-ricerca': 'Search radius',
    'ui.rapidissima': 'very fast',
    'ui.reali': 'Real',
    'ui.registra-il-cielo': 'Record the sky',
    'ui.registra-il-sistema-solare-3d': 'Record the 3D Solar System',
    'ui.registra-qualche-secondo-del-sistema-solare': 'Record a few seconds of the 3D Solar System to share',
    'ui.registrala-nel-diario-delle-tue-osservazioni': 'Record it in your observing logbook',
    'ui.registrazione-del-cielo': 'Sky recording',
    'ui.reticolo': 'Grid',
    'ui.rifai': 'Redo',
    'ui.rileva-di-nuovo-la-posizione-gps-poi-rete': 'Detect the position again: GPS, then network, then by hand',
    'ui.rilievo': 'Relief',
    'ui.rimetti-in-vista-il-punto-scelto': 'Bring the chosen point back into view',
    'ui.rimetti-la-vista-com-era-all-apertura-stessa': 'Restore the view as it was on opening: same framing, same zoom (or press R)',
    'ui.rimetti-la-vista-come-all-apertura': 'Restore the view as it was on opening',
    'ui.rimuovi': 'Remove',
    'ui.rinfresca-la-fotografia-da-solo-quando': 'Refreshes the snapshot on its own when it grows stale: every 45 seconds with drawing on, every three minutes when the data only sits in memory',
    'ui.ripristina-backup': 'Restore backup',
    'ui.riproduci': 'Play',
    'ui.rotta-dellaereo': 'Aircraft route',
    'ui.ruota-la-bussola-verso-est': 'Turn the compass east',
    'ui.ruota-la-bussola-verso-ovest': 'Turn the compass west',
    'ui.salva': 'Save',
    'ui.salva-evento': 'Save event',
    'ui.salva-le-mappe-per-l-uso-offline': 'Save the maps for offline use',
    'ui.salva-nel-diario': 'Save to the logbook',
    'ui.satellite': 'Satellite',
    'ui.satelliti': 'Satellites',
    'ui.scarica-i-prossimi-12-mesi': 'Download the next 12 months',
    'ui.scarica-il-file-sul-dispositivo': 'Download the file to this device',
    'ui.scarica-le-tessere-della-mappa-attorno-a': 'Downloads the map tiles around this point: on eclipse day you might have no network',
    'ui.scegli-cartella': 'Choose folder',
    'ui.scegli-il-luogo-da-cui-stai-osservando': 'Choose where you are observing from',
    'ui.scegli-la-cartella-che-contiene-i-video-da': 'Choose the folder that holds the videos to show.',
    'ui.scegli-la-durata-dei-video-creati-dal-tasto': 'Choose the length of the videos made by the planetarium’s red button.',
    'ui.scegli-sulla-mappa-il-punto-da-cui-guardare': 'Choose on the map the point to watch the sky from',
    'ui.scegli-tu-il-luogo': 'Choose the place yourself',
    'ui.scegli-un-punto-sulla-mappa-per-vedere-cosa': 'Choose a point on the map to see what happens there.',
    'ui.scegli-una-cartella-esistente': 'Choose an existing folder',
    'ui.schermo': 'Display',
    'ui.schermo-intero': 'Full screen',
    'ui.scorri-il-tempo': 'Scrub through time',
    'ui.scorri-il-tempo-dentro-la-finestra-scelta': 'Scrub through time within the chosen window',
    'ui.scrivi-le-prime-lettere-l-elenco-si-stringe': 'Type the first few letters: the list narrows. Enter picks the first.',
    'ui.se-il-gps-non-risponde-nessun-permesso-ma': 'If the GPS does not answer: no permission needed, but it can be tens of kilometres out.',
    'ui.secondi': 'seconds',
    'ui.segna-sulla-mappa-gli-eventi-in-corso-all': 'Marks on the map the events under way at the hour shown: a shower’s radiant, the eclipsed body, the bodies in a conjunction',
    'ui.segna-visto-su-un-evento-dell-agenda-e': 'Mark “Seen!” on an event in the agenda and it ends up here, with your note.',
    'ui.segni-e-aiuti': 'Markers and guides',
    'ui.segui-il-telefono': 'Follow the phone',
    'ui.segui-l-ombra': 'Follow the shadow',
    'ui.sei-banchi-di-prova-con-dentro-le-posizioni': 'Six benches built around the real positions of the planets, to understand the six things behind everything else in the app: why the planets sometimes go backwards, which three rules govern every orbit, how you gain speed by passing close to a planet, why you can only set off for Mars every twenty-six months, when the planets really do line up, and how the Sun manages to light an aurora on the other side of the planet. Each bench ends with buttons that take the same thing into the planetarium and into the 3D Solar System.',
    'ui.sempre-disponibile': 'always available',
    'ui.serve-per-gli-orari-di-sorgere-e-tramonto-il': 'Needed for rise and set times, astronomical darkness, the weather and ISS passes',
    'ui.serve-per-orari-di-sorgere-e-tramonto-buio': 'Needed for rise and set times, astronomical darkness, the weather and space-station passes. It can be detected by GPS, inferred from your connection, or chosen by hand.',
    'ui.sezioni-delle-impostazioni': 'Settings sections',
    'ui.siamo-un-modo-per-il-cosmo-di-conoscere-se': '“We are a way for the cosmos to know itself.”',
    'ui.sicurezza': 'Safety',
    'ui.simula-una-tempesta': 'Simulate a storm',
    'ui.simulazione': 'Simulation',
    'ui.sistema-solare-3d': '3D Solar System',
    'ui.sole-coperto': 'Sun covered',
    'ui.sole-e-luna': 'Sun and Moon',
    'ui.sopra-le-linee-la-figura-il-cacciatore-il': 'Over the lines, the figure: the hunter, the lion, the ship. It is a light veil laid over the real stars — at wide field it is barely hinted at, and zoom in far enough and it fades away by itself. Tap a figure on the map to open its page',
    'ui.sotto-l-orizzonte': 'Below the horizon',
    'ui.sovrapponi-il-cielo-all-immagine-della': 'Overlay the sky on the camera image: the field of view becomes that of the lens, and a pinch calibrates it',
    'ui.spostamento-geografico-della-vista-apri-la': 'Geographic shift of the view. Open the interactive map full screen',
    'ui.stanotte': 'Tonight',
    'ui.stasera': 'Tonight',
    'ui.stazioni-spaziali': 'Space stations',
    'ui.stelle': 'Stars',
    'ui.sto-preparando-il-cielo-5-044-stelle-in': 'Preparing the sky: 5,044 stars on their way…',
    'ui.stop': 'Stop',
    'ui.strumento-usato': 'Instrument used',
    'ui.su-ora': 'Up now',
    'ui.tara-su-un-astro': 'Calibrate on an object',
    'ui.tele-scopio': 'Tele­scope',
    'ui.tempo': 'Time',
    'ui.terra-e-luna': 'Earth and Moon',
    'ui.terreno-vero': 'Real terrain',
    'ui.tiene-la-mappa-centrata-sull-ombra-mentre': 'Keeps the map centred on the shadow as it runs',
    'ui.tiene-vivo-il-feed-ads-b-spegnendolo-si': 'Keeps the ADS-B feed alive. Switch it off and the requests stop and the snapshot is discarded',
    'ui.tieni-al-centro-l-oggetto-scelto-la-vista-lo': 'Keep the chosen object centred: the view follows it on its own',
    'ui.tieni-l-oggetto-selezionato-sempre-al-centro': 'Keep the selected object always at the centre of the map: the view follows it as the sky turns or as playback runs',
    'ui.tienila-visibile-fino-al-prossimo-punto': 'Keep it visible until the next point is pressed in the planetarium',
    'ui.titolo': 'Title *',
    'ui.tocca-per-esplorare': 'Tap to explore',
    'ui.tocca-un-punto-qualunque-del-mappamondo-per': 'Tap anywhere on the globe to choose it, or tap it twice to go there straight away: the planetarium will draw the sky from that spot. Your app position is left untouched.',
    'ui.tocca-una-citta-per-portare-li-il-tuo-punto': 'Tap a town to move your observing point there.',
    'ui.toccane-uno-la-mappa-lo-porta-al-centro-e': 'Tap one: the map brings it to the centre and an arrow guides you. For its data card, tap it on the map.',
    'ui.togli-lintervallo': 'Clear the range',
    'ui.torna-al-campo-visivo-di-partenza-55-con-la': 'Return to the starting field of view, 55° (with the camera on: resets the lens calibration)',
    'ui.torna-al-kp-misurato-dal-noaa-per-quest-ora': 'Return to the Kp measured by NOAA for this hour',
    'ui.torna-al-planetario': 'Back to the planetarium',
    'ui.torna-alla-bussola-del-telefono-senza': 'Return to the phone’s compass, with no corrections',
    'ui.traccia': 'Track',
    'ui.trascina-per-girare-tocca-un-pianeta-doppio': 'Drag to rotate · tap a planet · double-tap the Earth to set the yellow marker',
    'ui.trascina-per-scorrere-il-tempo': 'Drag to scrub through time',
    'ui.trascina-per-scorrere-il-tempo-dentro-la': 'Drag to scrub through time within the chosen window',
    'ui.trascina-per-spostarti-nel-tempo': 'Drag to move through time',
    'ui.trova-il-punto-migliore': 'Find the best spot',
    'ui.trova-la-mia-posizione': 'Find my position',
    'ui.tutte-e-ottantotto-la-figura-il-disegno-i': 'All eighty-eight: the figure, the artwork, the names from other cultures',
    'ui.tutte-le-costellazioni': '← All constellations',
    'ui.tutte-le-eclissi-solari-visibili-da-questo': 'Every solar eclipse visible from this point, up to 2070',
    'ui.tutte-le-eclissi-solari-visibili-dalla-tua': 'Every solar eclipse visible from your location',
    'ui.tutte-le-eclissi-visibili-da-qui': 'Every eclipse visible from here',
    'ui.tutti-i-dati-di-questo-oggetto': 'All the data for this object',
    'ui.tutti-i-prossimi': 'All upcoming',
    'ui.tutto': 'Everything',
    'ui.tutto-il-sistema-fino-a-nettuno-e-alla': 'The whole system, out to Neptune and the Kuiper belt',
    'ui.usa-queste-coordinate': 'Use these coordinates',
    'ui.vai': 'Go',
    'ui.vai-al-mese': 'Go to month',
    'ui.vale-solo-per-il-planetario-orari-meteo': 'This applies to the planetarium only: timings, weather, space-station passes and the telescope stay on your own position, the one in Settings.',
    'ui.vede-il-momento-del-massimo': 'Sees the moment of maximum',
    'ui.vede-l-eclissi-per-intero': 'Sees the eclipse in full',
    'ui.veloce': 'fast',
    'ui.velocita': 'Speed',
    'ui.velocita-della-simulazione': 'Simulation speed',
    'ui.vista-pulita': 'Clean view',
    'ui.visualizzazione': 'Display',
    'ui.zenit': 'Zenith',
  }
};
