/* Il dizionario italiano — la lingua sorgente del progetto.
 *
 * È un file di dati, come i `dati-*.js`: si carica come `<script>` prima di
 * `i18n.js`, che lo assorbe in memoria all'avvio. Da lì in poi ogni `t(chiave)`
 * è una lettura da `Map`, e il cambio lingua non costa nessuna richiesta e
 * nessun conto.
 *
 * Perché non `it.json`: questa applicazione si apre anche con un doppio clic su
 * `index.html`, e da `file://` una `fetch('it.json')` è vietata dal browser —
 * la lingua non arriverebbe. Il contenuto è comunque un oggetto piatto
 * chiave→testo, cioè JSON con una riga di intestazione.
 *
 * Questo è il dizionario di **ripiego**: quando una chiave manca nella lingua
 * scelta, il gestore torna qui. Una chiave che manca *anche* qui è un difetto,
 * e si vede — sullo schermo compare il nome della chiave.
 *
 * Tre cose da sapere prima di aggiungerne una:
 *   - i segnaposto sono `{nome}`; `{n}` è il numero e si scrive col separatore
 *     della lingua (mille virgola cinque qui, mille punto cinque in inglese);
 *   - una voce che dipende da una quantità si scrive `{ uno: …, altri: … }`, e
 *     a scegliere è `Intl.PluralRules`, non noi;
 *   - le chiavi `ui.*` nascono dallo slug della frase italiana: sono generate,
 *     e chi ne aggiunge una a mano faccia lo stesso, così restano leggibili in
 *     `index.html`.
 */

window.ASTRO_DIZIONARI = window.ASTRO_DIZIONARI || {};
window.ASTRO_DIZIONARI['it'] = {
  locale: 'it-IT',
  nome: 'Italiano',
  manifest: 'manifest.json',
  messaggi: {
    // --- Il nucleo, il tempo e i punti cardinali ---------------------
    'lingua.cambio': 'Passa a {lingua}',
    'app.titolo': 'AstroCalendario di Ben',
    'tempo.adesso': 'adesso',
    'tempo.passato': 'passato',
    'tempo.istanti': 'fra pochi istanti',
    'tempo.fra': 'fra {durata}',
    'tempo.fa': '{durata} fa',
    'tempo.fraSecondi': { uno: 'fra {n} secondo', altri: 'fra {n} secondi' },
    'tempo.breveSecondi': 'fra {n} s',
    'tempo.breveMinuti': 'fra {n} min',
    'tempo.breveOre': 'fra {n} h',
    'tempo.fraMinuti': { uno: 'fra {n} minuto', altri: 'fra {n} minuti' },
    'tempo.fraMinutiSecondi': 'fra {n} min {s} s',
    'tempo.fraOre': { uno: 'fra un\'ora', altri: 'fra {n} ore' },
    'tempo.fraOreMinuti': 'fra {n} h {m} min',
    'tempo.fraGiorni': { uno: 'fra {n} giorno', altri: 'fra {n} giorni' },
    'tempo.fraMesi': { uno: 'fra {n} mese', altri: 'fra {n} mesi' },
    'tempo.fraAnni': { uno: 'fra un anno', altri: 'fra {n} anni' },
    'tempo.fraAnniMesi': { uno: 'fra {n} anni e un mese', altri: 'fra {n} anni e {m} mesi' },
    'tempo.unitaGiorni': '{n} g',
    'tempo.unitaOre': '{n} h',
    'tempo.unitaMinuti': '{n} min',
    'tempo.unitaSecondi': '{n} s',
    'tempo.inCorsoOAppenaPassata': 'in corso o appena passata',
    'punto.sigla.n': 'N',
    'punto.sigla.nne': 'NNE',
    'punto.sigla.ne': 'NE',
    'punto.sigla.ene': 'ENE',
    'punto.sigla.e': 'E',
    'punto.sigla.ese': 'ESE',
    'punto.sigla.se': 'SE',
    'punto.sigla.sse': 'SSE',
    'punto.sigla.s': 'S',
    'punto.sigla.ssw': 'SSO',
    'punto.sigla.sw': 'SO',
    'punto.sigla.wsw': 'OSO',
    'punto.sigla.w': 'O',
    'punto.sigla.wnw': 'ONO',
    'punto.sigla.nw': 'NO',
    'punto.sigla.nnw': 'NNO',
    'punto.nome.n': 'nord',
    'punto.nome.ne': 'nord-est',
    'punto.nome.e': 'est',
    'punto.nome.se': 'sud-est',
    'punto.nome.s': 'sud',
    'punto.nome.sw': 'sud-ovest',
    'punto.nome.w': 'ovest',
    'punto.nome.nw': 'nord-ovest',

    // --- Il tempo, e i capolinea ---------------------------------------
    'tempo.capolinea': 'La macchina del tempo va dal {da} al {a}.',

    // --- La scheda di un astro (skyRigheScheda) ------------------------
    'scheda.tipo': 'Tipo',
    'scheda.fase': 'Fase',
    'scheda.discoIlluminato': 'disco illuminato al {n}%',
    'scheda.magnitudine': 'Magnitudine',
    'scheda.illuminazione': 'Illuminazione',
    'scheda.alSole': 'al Sole, quindi può brillare',
    'scheda.nellOmbraDellaTerra': 'dentro l\'ombra della Terra, invisibile',
    'scheda.direzione': 'Direzione',
    'scheda.direzioneAzimut': '{punto} (azimut {az}°)',
    'scheda.altezza': 'Altezza',
    'scheda.sopraOrizzonte': '{gradi}° sopra l\'orizzonte',
    'scheda.sottoOrizzonte': '{gradi}° sotto l\'orizzonte',
    'scheda.daQui': 'Da qui',
    'scheda.circumpolare': 'è circumpolare: non tramonta mai',
    'scheda.nonSorgeMai': 'non sale mai sopra l\'orizzonte, a questa latitudine',
    'scheda.sorgeTramonta': 'Sorge e tramonta',
    'scheda.codiceCatalogo': 'Codice catalogo',
    'scheda.costellazione': 'Costellazione',
    'scheda.distanzaTerra': 'Distanza dalla Terra',
    'scheda.dimensioni': 'Dimensioni',
    'scheda.temperatura': 'Temperatura',
    'scheda.kelvinInSuperficie': 'circa {k} K in superficie',
    'scheda.ilSoleNeHa': 'il Sole ne ha 5800',
    'scheda.indiceColore': 'Indice di colore',
    'scheda.bv': 'B−V {v}',
    'scheda.bvSpiegazione': 'quanto è più luminosa nel blu che nel giallo',
    'scheda.distanzaSole': 'Distanza dal Sole',
    'scheda.unitaAstronomiche': '{n} unità astronomiche',
    'scheda.laLuceCiMette': 'la luce ci mette {tempo}',
    'scheda.distanzaSoleInCielo': 'Distanza dal Sole in cielo',
    'scheda.troppoVicinoAlSole': 'troppo vicino: se ne sta nella luce del crepuscolo',
    'scheda.orbita': 'Orbita',
    'scheda.unGiroOgniMinuti': 'un giro della Terra ogni {n} minuti',
    'scheda.coordinate': 'Coordinate',
    'scheda.arDec': 'AR {ar} · Dec {dec}',
    'scheda.epocaDiOggi': 'epoca di oggi',
    'scheda.rispettoEclittica': 'Rispetto all\'eclittica',
    'scheda.sullaLinea': 'praticamente sulla linea',
    'scheda.gradiSopra': '{gradi}° sopra',
    'scheda.gradiSotto': '{gradi}° sotto',
    'scheda.longitudine': 'longitudine {n}°',
    'scheda.passaPiuAlto': 'Passa più alto',
    'scheda.aGradiDiAltezza': ', a {gradi}° di altezza',

    // --- Le categorie degli eventi e gli strumenti ---------------------
    'categoria.luna': 'Fasi Lunari',
    'categoria.eclissi': 'Eclissi',
    'categoria.stagioni': 'Stagioni',
    'categoria.meteore': 'Sciami Meteorici',
    'categoria.pianeti': 'Pianeti',
    'categoria.congiunzioni': 'Congiunzioni',
    'categoria.aurore': 'Aurore',
    'categoria.personali': 'Personali',
    'strumento.occhio': 'A occhio nudo',
    'strumento.binocolo': 'Con binocolo',
    'strumento.telescopio': 'Con telescopio',
    'filtro.tutti': 'Tutti',
    'filtro.tutto': 'Tutto',
    'filtro.tutteLeCategorie': 'Tutte le categorie insieme',
    'filtro.mostraStrumento.tutti': 'Mostra ciò che si vede in ogni caso',
    'filtro.mostraStrumento.occhio': 'Mostra ciò che si vede a occhio nudo',
    'filtro.mostraStrumento.binocolo': 'Mostra ciò che si vede col binocolo',
    'filtro.mostraStrumento.telescopio': 'Mostra ciò che si vede col telescopio',

    // --- La scheda di un aereo e lo stato del feed ADS-B ---------------
    'aereo.volo': 'Volo',
    'aereo.registrazione': 'Registrazione',
    'aereo.aeromobile': 'Aeromobile',
    'aereo.operatore': 'Operatore',
    'aereo.quota': 'Quota',
    'aereo.velocita': 'Velocità',
    'aereo.rotta': 'Rotta',
    'aereo.distanza': 'Distanza',
    'aereo.inVista': 'In vista',
    'aereo.itinerario': 'Itinerario',
    'aereo.icao': 'Codice ICAO',
    'aereo.squawk': 'Squawk',
    'aereo.finoAAltezza': ', fino a {gradi}° di altezza',
    'aereo.ancoraPoiTramonta': 'ancora {quanto}{alto}, poi tramonta',
    'aereo.almeno': 'almeno {quanto}{alto}',
    'aereo.posizioneStimata': 'Posizione stimata dalla rotta, velocità e salita dell’ultima lettura ADS-B.',
    'aereo.posizioneAllineata': 'Posizione allineata al feed ADS-B in tempo reale.',
    'aereo.ricercaInCorso': 'ricerca in corso…',
    'aereo.tracciaSullaMappa': 'Traccia reale sulla mappa',
    'aereiStato.quanti': { uno: '1 aereo', altri: '{n} aerei' },
    'aereiStato.nuovoScarico': ' · nuovo scarico {quando}',
    'aereiStato.senzaPosizione': 'Serve una posizione per cercare gli aerei.',
    'aereiStato.proxyMancante': 'Nessun dato: le reti ADS-B non autorizzano le richieste dei browser e in questo momento non risponde nemmeno un ponte CORS pubblico. Per una strada che non dipende da servizi di terzi si configura un proxy proprio (ADSB_PROXY_URL, vedi ADSB-PROXY.md).',
    'aereiStato.spento': 'Dati in pausa: accendi «Dati ADS-B» per scaricare il traffico vicino.',
    'aereiStato.spentoConDati': 'Dati in pausa · ultima lettura {eta} ({quanti}).',
    'aereiStato.carico': 'Primo scarico dei dati ADS-B in corso…',
    'aereiStato.caricoConDati': 'Aggiornamento in corso… · intanto {quanti} dall\'ultima lettura {eta}.',
    'aereiStato.passato': 'Macchina del tempo: {quanti} in posizione stimata dall\'ultima lettura ADS-B. Torna ad Adesso per i dati in tempo reale.',
    'aereiStato.senzaRete': 'Senza rete: i dati ADS-B arriveranno appena torna la connessione.',
    'aereiStato.senzaReteConDati': 'Senza rete · resta l\'ultima lettura di {eta} ({quanti}).',
    'aereiStato.riprovo': ' Riprovo {quando}.',
    'aereiStato.errore': 'Dati ADS-B non disponibili ({guaio}).{riprova}',
    'aereiStato.erroreConDati': 'Aggiornamento non riuscito ({guaio}): resta l\'ultima lettura di {eta} ({quanti}).{riprova}',
    'aereiStato.vecchio': '{quanti} · ultima lettura {eta}: posizioni propagate dalla rotta.{prossimo}',
    'aereiStato.primoScarico': 'In attesa del primo scarico ADS-B…',
    'aereiStato.normale': '{quanti} · {fonte} · aggiornato {eta}{prossimo}',

    // --- Il fumetto dell'aereo e i suoi comandi ------------------------
    'aereo.nonComunicata': 'non comunicata',
    'aereo.partenza': 'Partenza',
    'aereo.destinazione': 'Destinazione',
    'aereo.aereo': 'Aereo',
    'aereo.metriSlm': '{n} m s.l.m.',
    'aereo.distanzaReale': 'Distanza reale',
    'aereo.apriPannello': '{nota}. Apri il pannello degli aerei ADS-B',
    'aereo.nonRiuscito': 'Non riuscito',
    'aereo.aggiornato': 'Aggiornato ✓',
    'aereo.aggiornamento': 'Aggiornamento…',
    'aereo.cartaServeRete': 'La carta geografica richiede la rete al primo utilizzo.',
    'aereo.tracciaAdsbDi': 'Traccia ADS-B di {volo}',
    'aereo.nonDisponibile': 'non disponibile',

    // --- La scheda di una stella e del cielo profondo ------------------
    'profondo.volteLunaPiena': '{n} volte la Luna piena',
    'profondo.comeLunaPiena': 'grande come la Luna piena',
    'profondo.terzoLunaPiena': 'un terzo della Luna piena',
    'stella.classe': 'Stella {colore}',
    'stella.classeDedotta': 'classe {classe} circa, dedotta dal colore',
    'stella.colore.O': 'azzurra',
    'stella.colore.B': 'azzurra',
    'stella.colore.A': 'bianco-azzurra',
    'stella.colore.F': 'bianca',
    'stella.colore.G': 'gialla',
    'stella.colore.K': 'arancione',
    'stella.colore.M': 'rossa',
    'stella.piuCalda': 'più calda del Sole',
    'stella.piuFredda': 'più fredda del Sole',
    'stella.quasiComeIlSole': 'calda quasi quanto il Sole',
    'stella.notaColore': 'Il colore non è un dettaglio estetico: dice la temperatura. Questa è {colore}, sui {gradi} gradi in superficie — {confronto}, che ne ha 5800.',
    'stella.notaGigante': 'Una rossa così visibile a occhio nudo è quasi certamente una gigante: le nane rosse sono la maggioranza delle stelle della Galassia, ma nessuna si vede senza telescopio.',
    'stella.notaAzzurra': 'Le azzurre bruciano in fretta e vivono poco: qualche decina di milioni di anni, contro i dieci miliardi del Sole.',
    'lune.transito': '{luna} sta passando davanti a Giove',
    'lune.ombra': 'l\'ombra di {luna} è sul disco di Giove',
    'lune.occultata': '{luna} è nascosta dietro Giove',
    'lune.eclissata': '{luna} è nel cono d\'ombra di Giove',
    'lune.tutteNascoste': 'tutte e quattro nascoste da Giove',
    'meteo.nonAncoraDisponibili': 'Previsioni non ancora disponibili.',

    // --- Il racconto della curva dell'altezza --------------------------
    'curva.servePosizione': 'Serve la posizione per sapere quando sale.',
    'curva.soloDiGiorno': 'Stanotte non arriva mai sopra l\'orizzonte a cielo buio: sta su di giorno.',
    'curva.nonSorgeMai': 'Stanotte non sorge mai da qui.',
    'curva.quasiTuttaLaNotte': 'per quasi tutta la notte',
    'curva.circaOre': 'per circa {n} ore',
    'curva.pocoPiuDiUnOra': 'per poco più di un\'ora',
    'curva.menoDiUnOra': 'per meno di un\'ora',
    'curva.momentoBuono': 'Il momento buono è verso le {ora}, a {gradi}° sull\'orizzonte. Utilizzabile {quanto}.',

    // --- Il tasto dei filtri -------------------------------------------
    'ui.filtri': 'Filtri',
    'ui.mostraFiltri': 'Mostra i filtri per categoria e strumento',
    'ui.nascondiFiltri': 'Nascondi i filtri',

    // --- La dashboard di Stasera e le Impostazioni ---------------------
    'ui.apri-la-mappa-a-tutto-schermo': 'Apri la mappa a tutto schermo',
    'stasera.vedilaNelPlanetario': 'Vedila nel planetario',
    'stasera.servePosizione': 'Serve la posizione per sapere cosa hai sopra la testa.',
    'stasera.dimmiDoveSono': 'Dimmi dove sono',
    'stasera.nienteAbbastanzaAlto': 'Stanotte non c\'è niente che salga abbastanza da qui.',
    'stasera.aprilNelPlanetario': 'Aprilo nel planetario, con la mappa puntata su di lui',
    'stasera.puntiSu100': '{n} su 100',
    'stasera.versoLeAGradi': 'verso le {ora}, a {gradi}°',
    'bersaglio.pianeta': 'pianeta',
    'bersaglio.cometa': 'cometa',
    'bersaglio.asteroide': 'asteroide',
    'cielo.bortleTitolo': 'Bortle {b}: si arriva a vedere fino alla magnitudine {mag}',
    'cielo.scalaBortle': 'Scala di Bortle {b}: a occhio nudo si arriva alla magnitudine {mag}',
    'cielo.cioeStelle': ', cioè circa {n} stelle in tutto il cielo.',
    'raggi.spenti': 'spenti',
    'raggi.stoCercando': 'sto cercando…',
    'raggi.nonRiuscito': 'non sono riuscito a cercare',
    'raggi.apriIlPlanetario': 'apri il planetario per cercare',
    'raggi.nienteQuiAttorno': 'niente qui attorno',
    'raggi.inVista': ' · {n} in vista',

    // --- Il meteo, gli ostacoli e i raggi di ricerca -------------------
    'meteo.nonRiescoAGiudicare': 'Non riesco a giudicare le prossime notti.',
    'meteo.stoScaricando': 'Sto scaricando le previsioni…',
    'meteo.finestraMigliore': 'Finestra migliore: {testo}.',
    'orizzonte.altezzaOstacoli': 'Altezza degli ostacoli verso {dove}, in gradi',
    'raggi.senzaMappa': 'La mappa non si è caricata (serve la rete la prima volta). I raggi si regolano con la slitta qui sotto.',
    'raggi.senzaPosizione': 'Non so ancora dove sei: scegli una posizione e la mappa comparirà. Intanto i raggi si regolano con la slitta.',
    'raggi.anelloTratteggiato': ' Entro {km} km {dentro}; oltre, {fuori} — è l\'anello tratteggiato.',
    'raggi.notaAccesi': 'Montagne, paesi e acque arrivano da OpenStreetMap; gli aerei sono aggiornati in tempo reale tramite ADS-B.',
    'raggi.notaSpenti': 'I nomi delle montagne sono spenti: l\'orizzonte resta la forma del terreno, senza scritte. Si accendono anche dal pannello Visualizzazione del planetario.',

    // --- I motivi di un bersaglio e il giudizio della notte ------------
    'motivo.restaBasso': 'resta basso, arriva solo a {gradi}°',
    'motivo.nonSaleMolto': 'non sale molto ({gradi}°)',
    'motivo.saleFinoA': 'sale fino a {gradi}°',
    'motivo.mezzOra': 'poco più di mezz\'ora di finestra utile',
    'motivo.finestraStretta': 'finestra stretta, circa {n} ore',
    'motivo.serveIlTelescopio': 'serve il telescopio',
    'motivo.magnitudine': 'magnitudine {mag}',
    'motivo.quasiImpossibile': 'col tuo cielo è quasi impossibile',
    'notte.lunaSottoOrizzonte': 'Luna sotto l\'orizzonte: cielo al suo meglio',
    'notte.lunaAlPerCento': 'Luna al {perc}% e a {gradi}° sull\'orizzonte',
    'notte.sereno': 'cielo sereno',
    'notte.aTratti': 'nuvole a tratti',
    'notte.moltoNuvoloso': 'molto nuvoloso',
    'notte.coperto': 'coperto',
    'notte.senzaLuna': 'senza Luna',
    'notte.lunaSchiarisce': 'con la Luna che schiarisce tutto',
    'notte.unPoDiLuna': 'con un po\' di Luna',
    'notte.daUnCielo': 'da un cielo «{cielo}»',

    // --- La barra del terreno, l'atlante e la scheda della posizione ---
    'terreno.stoMisurando': 'Sto misurando {che}… {per}%',
    'terreno.pronto': 'Il terreno attorno a te è pronto.',
    'terreno.ilTerreno': 'il terreno',
    'terreno.elencoFinale': '{prime} e {ultima}',
    'terreno.fase.quote': 'la forma del terreno',
    'terreno.fase.citta': 'le luci dei paesi',
    'terreno.fase.cime': 'i nomi delle montagne',
    'terreno.fase.acque': 'i laghi e i fiumi',
    'terreno.fase.rilievo': 'il rilievo del terreno',
    'atlante.filtro.tutte': 'Tutte',
    'atlante.filtro.australi': 'Cielo australe',
    'atlante.filtro.boreali': 'Cielo boreale',
    'atlante.filtro.disegni': 'Con disegno',
    'atlante.filtro.qui': 'Si vedono da qui',
    'atlante.filtro.buio': 'Del buio',
    'posizione.diRipiego': 'È una posizione di ripiego: va bene per gli orari, ma se il paese non è quello giusto scegli la città qui sotto.',
    'posizione.sceltaDaTe': 'L\'app sta calcolando tutto da qui. L\'hai scelta tu, quindi resta: né il GPS né la rete la cambiano da soli, finché non premi “Rileva di nuovo”.',
    'posizione.calcoloDaQui': 'L\'app sta calcolando tutto da qui.',
    'sol.senzaLibreria': 'Senza la libreria di calcolo non si possono mettere i pianeti al loro posto.',

    // --- I sei quadri della lezione dell'eclittica ---------------------
    'lezione.alto.breve': 'Dall\'alto',
    'lezione.alto.titolo': 'Visto dall\'alto sembra un bersaglio',
    'lezione.alto.testo': 'Sopra la testa del Sole il Sistema Solare sembra un bersaglio: cerchi quasi perfetti, percorsi tutti nello stesso verso, come se qualcuno li avesse disegnati col compasso. È la figura che tutti abbiamo in mente — ed è anche quella che nasconde il fatto più importante, perché vista da sopra una cosa piatta e una cosa spessa sono identiche.',
    'lezione.taglio.breve': 'Di taglio',
    'lezione.taglio.titolo': 'Girata di taglio: non è una palla, è un disco',
    'lezione.taglio.testo': 'Adesso la stessa scena si abbassa fino a guardarla di profilo, e i cerchi si schiacciano uno sull\'altro. Ecco il fatto: i pianeti non sono sparsi in tutte le direzioni attorno al Sole, stanno tutti dentro a un piatto sottile. Ognuno viaggia su un piano un po\' diverso, ma «un po\'» vuol dire pochi gradi.',
    'lezione.piano.breve': 'Il piano',
    'lezione.piano.titolo': 'Il pavimento del Sistema Solare',
    'lezione.piano.testo': 'Per misurare quei gradi serve un pavimento da cui contarli, e la scelta è naturale: il piano dell\'orbita della Terra, cioè il nostro. Prolungalo all\'infinito, fino alle stelle: il cerchio che disegna nel cielo è <strong>l\'eclittica</strong>. Le orbite degli altri lo attraversano appena inclinate — Mercurio 7,0°, Venere 3,4°, Saturno 2,5°, Marte 1,8°, Giove 1,3° — e per questo restano sempre lì attorno.',
    'lezione.daQui.breve': 'Da qui',
    'lezione.daQui.titolo': 'Come lo vediamo da dentro',
    'lezione.daQui.testo': 'Noi stiamo dentro a quel pavimento e lo guardiamo di taglio: perciò il Sole, la Luna e i pianeti ci sembrano infilati sulla stessa riga, che attraversa il cielo da un orizzonte all\'altro. È esattamente la linea che accende il tasto «Eclittica» del planetario. Questi sono i pianeti veri di adesso: la scala verticale è ingrandita sei volte, altrimenti quei due o tre gradi non si vedrebbero.',
    'lezione.analemma.breve': 'L\'analemma',
    'lezione.analemma.titolo': 'L\'eclittica guardata sempre alla stessa ora',
    'lezione.analemma.testo': 'Prova a uscire ogni giorno alla stessa ora e a segnare dov\'è il Sole. Non viene un punto — e nemmeno una riga: viene un <strong>otto allungato</strong>, l\'analemma. Le due cause sono le stesse di prima, prese una per volta. L\'asse della Terra è inclinato di 23,4°, e questo alza e abbassa il Sole di 47° fra i due solstizi: è l\'altezza dell\'otto. L\'orbita è un\'ellisse, quindi d\'inverno la Terra corre più forte e il Sole arriva al mezzogiorno con un anticipo o un ritardo che tocca il quarto d\'ora: è la larghezza. Sulla mappa lo trovi acceso insieme all\'eclittica, in oro pallido, e ti passa esattamente per dove il Sole si trova adesso.',
    'lezione.nome.breve': 'Il nome',
    'lezione.nome.titolo': 'Perché si chiama proprio “eclittica”',
    'lezione.nome.testo': 'Il nome viene dalle eclissi. La Luna gira su un piano inclinato di 5° sul nostro, quindi tocca l\'eclittica in due soli punti: i <strong>nodi</strong>. Perché ci sia un\'eclissi servono due coincidenze insieme — la Luna in un nodo, e il Sole nella stessa direzione (eclissi di Sole) o in quella opposta (eclissi di Luna). Guarda il Sole girare attorno: solo due volte l\'anno si mette in linea con i nodi, ed è lì che si aprono le stagioni delle eclissi. Ecco perché non ne capita una al mese. L\'inclinazione dell\'orbita lunare, qui, è disegnata quattro volte più marcata del vero: a 5° esatti sarebbe indistinguibile dallo spessore della linea.',

    // --- Le fasi lunari ------------------------------------------------
    'fase.0.titolo': 'Luna Nuova',
    'fase.0.spiegazione': 'La Luna si trova tra la Terra e il Sole. La faccia rivolta verso di noi è in ombra: cielo buio, ottimo per osservare le stelle profonde.',
    'fase.0.cosaPortare': 'Telescopio per galassie e nebulose, essendo il cielo molto buio.',
    'fase.0.doveVederlo': 'Vai lontano dalla città per sfruttare il buio totale.',
    'fase.0.comeVederlo': 'Usa una mappa stellare per orientarti al buio.',
    'fase.1.titolo': 'Primo Quarto di Luna',
    'fase.1.spiegazione': 'Metà del disco lunare è illuminato. È il momento migliore per osservare i crateri lungo il terminatore, dove le ombre sono lunghe e nette.',
    'fase.1.cosaPortare': 'Binocolo o piccolo telescopio per i crateri.',
    'fase.1.doveVederlo': 'Visibile la sera, alta nel cielo dopo il tramonto.',
    'fase.1.comeVederlo': 'Osserva la linea di confine luce/ombra: è lì che i dettagli risaltano.',
    'fase.2.titolo': 'Luna Piena',
    'fase.2.spiegazione': 'La Terra si trova tra il Sole e la Luna. Il disco lunare è completamente illuminato e brillante.',
    'fase.2.cosaPortare': 'Binocolo per i mari lunari; un filtro lunare aiuta contro la luce intensa.',
    'fase.2.doveVederlo': 'Dovunque il cielo sia sgombro verso l’orizzonte.',
    'fase.2.comeVederlo': 'A occhio nudo la luce è intensa: un filtro lunare rende l’osservazione più confortevole.',
    'fase.3.titolo': 'Ultimo Quarto di Luna',
    'fase.3.spiegazione': 'L’altra metà del disco lunare è illuminata. Sorge a notte fonda ed è visibile al mattino presto.',
    'fase.3.cosaPortare': 'Binocolo o telescopio; sveglia presto per l’alba.',
    'fase.3.doveVederlo': 'Nel cielo del mattino, prima dell’alba.',
    'fase.3.comeVederlo': 'Approfitta del cielo scuro della seconda parte della notte per il deep sky.',

    // --- Il blocco «Da qui» delle schede dell'agenda -------------------
    'locale.servePosizione': 'Con la tua posizione posso dirti se questo evento si vede da casa tua, a che ora e in che direzione.',
    'locale.sorgeTramonta': 'Sorge {sorge} · tramonta {tramonta}',
    'locale.buioAstronomico': 'Buio astronomico quella notte: {da} → {a}',
    'locale.osservabilita': 'Osservabilità {punti}/100',
    'locale.momentoConsigliato': 'Momento consigliato: {quando}',
    'locale.sottoMaRecupera': 'Al momento del picco è sotto l\'orizzonte da qui, ma nella stessa notte arriva a {gradi}° verso le {ora}.',
    'locale.nonVisibile': 'Non visibile da qui: nell\'istante dell\'evento l\'astro si trova sotto l\'orizzonte.',
    'locale.cieloAncoraChiaro': 'All\'ora esatta dell\'evento il cielo è ancora chiaro (Sole a {sole}°)',
    'locale.guardaloVersoLe': ': guardalo verso le {ora}, quando è alto {gradi}° verso {dove}.',
    'locale.cercaNelBuio': '. Cerca l\'astro nelle ore di buio più vicine.',
    'locale.bassaSullOrizzonte': 'Visibile ma bassa sull\'orizzonte ({gradi}°): serve una vista libera verso {dove}.',
    'locale.benVisibile': 'Ben visibile da qui: {gradi}° sopra l\'orizzonte, verso {dove}.',

    // --- I consigli di astrofotografia ---------------------------------
    'foto.base.treppiede': 'Un treppiede (anche piccolo) fa più differenza di qualsiasi obiettivo costoso.',
    'foto.base.telefono': 'Col telefono: modalità Pro o Notte, autoscatto di 3 secondi per non muoverlo, messa a fuoco manuale su ∞.',
    'foto.luna.titolo': 'Fotografare la Luna',
    'foto.luna.obiettivo': 'Il più lungo che hai: 200–300 mm su reflex, zoom ottico sul telefono.',
    'foto.luna.esposizione': 'Regola “lunare”: 1/125 s, f/8, ISO 100. La Luna è illuminata dal Sole, quindi va trattata come un soggetto diurno.',
    'foto.luna.errore': 'L\'errore classico è sovraesporre: se viene un disco bianco senza crateri, riduci di 2–3 stop.',
    'foto.eclissi.titolo': 'Fotografare l\'eclissi',
    'foto.eclissi.obiettivo': 'Teleobiettivo 200 mm o più. Per quella solare serve un filtro solare certificato davanti all\'obiettivo.',
    'foto.eclissi.esposizione': 'Eclissi lunare: ISO 800, f/5.6, 1/4 s durante la totalità (la Luna rossa è molto più scura). Eclissi solare parziale: come una foto diurna, ma solo con filtro.',
    'foto.eclissi.errore': 'Mai puntare il Sole senza filtro: bruci il sensore e, se guardi nel mirino, anche l\'occhio.',
    'foto.meteore.titolo': 'Fotografare le stelle cadenti',
    'foto.meteore.obiettivo': 'Grandangolo luminoso (14–24 mm, f/2.8 o più aperto): serve campo, non ingrandimento.',
    'foto.meteore.esposizione': 'ISO 1600–3200, f/2.8, pose da 15–20 s a raffica per ore. Regola del 500: secondi massimi = 500 ÷ lunghezza focale, oltre le stelle diventano trattini.',
    'foto.meteore.errore': 'Non si insegue la meteora: si punta la camera in una zona di cielo a ~40° dal radiante e si scatta in continuo.',
    'foto.pianeti.titolo': 'Fotografare pianeti e congiunzioni',
    'foto.pianeti.obiettivo': 'Per la congiunzione basta un 50–100 mm: bello è il paesaggio con i due astri vicini.',
    'foto.pianeti.esposizione': 'ISO 400–800, f/4, 1–2 s se sono ancora nel crepuscolo. I pianeti sono luminosi: meglio esporre poco.',
    'foto.pianeti.errore': 'Includi un albero o un profilo di case: una foto di due puntini nel nero non racconta nulla.',
    'foto.cielo.titolo': 'Fotografare il cielo',
    'foto.cielo.obiettivo': 'Grandangolo luminoso e messa a fuoco manuale su una stella brillante.',
    'foto.cielo.esposizione': 'ISO 1600, f/2.8, 10–20 s. Scatta in RAW se puoi: recuperi molto in post-produzione.',
    'foto.cielo.errore': 'Evita lo zoom digitale: rovina i dettagli senza aggiungere nulla.',

    // --- Lo stato del planetario, la bussola e la barra del tempo ------
    'fonte.gps.breve': 'GPS',
    'fonte.gps.provenienza': 'rilevata dal GPS del dispositivo',
    'fonte.rete.breve': 'rete',
    'fonte.rete.provenienza': 'dedotta dalla connessione',
    'fonte.citta.breve': 'città scelta',
    'fonte.citta.provenienza': 'la città che hai scelto',
    'fonte.manuale.breve': 'a mano',
    'fonte.manuale.provenienza': 'le coordinate che hai scritto',
    'fonte.salvata.breve': 'salvata',
    'fonte.salvata.provenienza': 'l\'ultima posizione salvata',
    'fonte.backup.breve': 'da backup',
    'fonte.backup.provenienza': 'ripristinata da un backup',
    'stato.cieloVistoDa': 'Cielo visto da {dove} — vale solo nel planetario, la posizione dell\'app non cambia',
    'stato.posizione': 'Posizione: {dove}',
    'stato.posizioneNonRilevata': 'Posizione non ancora rilevata',
    'bussola.nessunSensore': 'Bussola: nessun sensore (la vista la muovi col dito)',
    'bussola.intestazione': 'Bussola: {fonte}',
    'bussola.fonte.quaternione': 'assetto completo dal sistema (nessuna posa degenere)',
    'bussola.fonte.evento': 'angoli di orientamento del browser',
    'bussola.fonte.ponte': 'giroscopio agganciato al Nord magnetico',
    'bussola.fonte.attesa': 'in attesa di una lettura',
    'bussola.tarataSu': 'tarata su {astro} ({gradi}°)',
    'bussola.correzioneManuale': 'correzione manuale {gradi}°',
    'bussola.declinazione': 'declinazione magnetica {gradi}°',
    'bussola.inaffidabile': 'il telefono la dichiara inaffidabile',
    'bussola.disturbata': 'disturbata di circa {gradi}°',
    'bussola.dettoAVoce': 'Vista verso {dove}, {gradi} gradi, campo inquadrato {campo}',
    'schermo.entra': 'Cielo a schermo intero',
    'schermo.esci': 'Esci da schermo intero',
    'barraTempo.aVoce': 'Ora del dispositivo {luogo}; {direzione}, {scarto}',
    'barraTempo.aVoceDueFusi': 'Ora della località {luogo}; ora attuale del dispositivo {dispositivo}; {direzione}, {scarto}',
    'barraTempo.titolo': '{esteso} · dispositivo {dispositivo}{scarto} — tocca per data, passo e velocità del playback',
    'barraTempo.tempoReale': ' (tempo reale)',
    'registra.fermaTitolo': 'Ferma qui la registrazione e tieni quello che hai ripreso',
    'registra.titoloCielo': 'Registra {n} secondi di cielo da condividere',
    'registra.titoloSolare': 'Registra {n} secondi del Sistema Solare 3D da condividere',
    'registra.ferma': 'Ferma la registrazione',
    'registra.cielo': 'Registra il cielo',
    'registra.solare': 'Registra il Sistema Solare 3D',

    // --- La cornice delle schede dell'agenda ---------------------------
    'agenda.tuttiInArrivo': 'Stai leggendo tutti gli eventi in arrivo. Scegli un mese per vedere quello, anche nel passato.',
    'agenda.simula': 'Simula',
    'agenda.simulaTitolo': 'Guarda cosa succede, passo per passo',
    'agenda.ascolta': 'Ascolta',
    'agenda.ascoltaTitolo': 'Leggi ad alta voce',
    'agenda.cosaSuccede': 'Cosa succede',
    'agenda.comePrepararsi': 'Come prepararsi',
    'agenda.portare': 'Portare',
    'agenda.dove': 'Dove',
    'agenda.come': 'Come',
    'agenda.strumentoConsigliato': 'Strumento consigliato',
    'azione.diarioTitolo': 'Registra l\'osservazione nel diario',
    'azione.visto': 'Visto!',
    'azione.segnaVisto': 'Segna come visto',
    'azione.condividi': 'Condividi',
    'azione.condividiTitolo': 'Condividi l\'evento',
    'azione.cartolina': 'Cartolina',
    'azione.cartolinaTitolo': 'Crea una cartolina da mandare in chat',
    'azione.calendario': 'Al calendario',
    'azione.calendarioTitolo': 'Aggiungi al calendario del telefono',

    // --- Le scorciatoie di un evento e le righe del mese ---------------
    'scorciatoia.planetario': 'Vedi nel planetario',
    'scorciatoia.planetarioTitolo': 'Apre il planetario sull\'istante dell\'evento, puntato dove guardare',
    'scorciatoia.posto': 'Trova il posto migliore',
    'scorciatoia.postoTitolo': 'Cerca entro il raggio scelto un punto in cui montagne e colline non coprono l\'evento',
    'scorciatoia.ombra': 'Mappa dell\'ombra',
    'scorciatoia.ombraTitolo': 'Il percorso del cono d\'ombra, minuto per minuto',
    'scorciatoia.doveQuando': 'Dove e quando vederla',
    'scorciatoia.doveQuandoTitolo': 'Da dove si vede, a che ora, e con la Luna quanto alta',
    'scorciatoia.perche': 'Perché succede',
    'scorciatoia.percheTitolo': 'La Terra e la Luna viste da fuori in quell\'istante, a scala vera, coi coni d\'ombra: perché quella sera l\'allineamento riesce',
    'mese.eventiDi': 'Eventi di {mese} {anno}, calcolati per questo mese.',
    'mese.staiLeggendo': 'Stai leggendo {mese} {anno}. Con “Tutti i prossimi” torni agli eventi in arrivo.',
    'mese.calcoloInCorso': 'Calcolo gli eventi di {mese} {anno}…',

    // --- Lo schermo intero del planetario ------------------------------
    'schermo.esciTitolo': 'Esci dallo schermo intero (anche con Esc)',

    // --- L'interfaccia statica di index.html -------------------------
    'ui.a-occhio-nudo': 'A occhio nudo',
    'ui.a-tutto-schermo': 'A tutto schermo',
    'ui.accelera-il-playback': 'Accelera il playback',
    'ui.accelera-il-tempo': 'Accelera il tempo',
    'ui.accendi-l-ovale-aurorale-boreale-o-australe': 'Accendi l\'ovale aurorale — boreale o australe, secondo l\'emisfero — messo in cielo dove sta davvero: se da qui si vede, e quanto se ne affaccia sopra l\'orizzonte, lo decide la curvatura della Terra. Accendendolo compaiono qui sotto la slitta della tempesta e la riga che dice cosa si vedrebbe da qui',
    'ui.aerei': 'Aerei',
    'ui.aerei-leggenda-rotte': '<span class="aereo-leggenda itinerario"></span> rotta ortodromica · <span class="aereo-leggenda osservata"></span> traccia reale ADS-B · <span class="aereo-leggenda prevista"></span> previsione 5 minuti',
    'ui.agenda': 'Agenda',
    'ui.aggiorna': 'Aggiorna',
    'ui.aggiorna-adesso': 'Aggiorna adesso',
    'ui.aggiornamento-automatico': 'Aggiornamento automatico',
    'ui.aggiunge-le-nuvole-previste-per-questo-luogo': 'Aggiunge le nuvole previste per questo luogo e quest\'ora all\'atmosfera',
    'ui.aggiungi-evento': 'Aggiungi evento',
    'ui.aggiungi-un-evento-tuo': 'Aggiungi un evento tuo',
    'ui.aiuti-disegnati-sopra-al-cielo': 'Aiuti disegnati sopra al cielo',
    'ui.all-oculare': 'All\'oculare',
    'ui.allineamento-delle-stelle-in-corso': 'Allineamento delle stelle in corso…',
    'ui.allineamento-puntamento-e-scaletta-per-il': 'Allineamento, puntamento e scaletta per il tuo telescopio',
    'ui.anno-si-puo-scrivere-fino-al-3000': 'Anno: si può scrivere, fino al 3000',
    'ui.annulla': 'Annulla',
    'ui.apre-il-planetario-sullo-stesso-momento-con': 'Apre il planetario sullo stesso momento, con il Sole eclissato in cielo',
    'ui.aprendo-la-galleria-verra-creata-la-cartella': 'Aprendo la galleria verrà creata la cartella “astrocalben”.',
    'ui.apri-il-pannello-degli-aerei-ads-b': 'Apri il pannello degli aerei ADS-B',
    'ui.apri-la-scheda-quando-il-mirino-giallo-resta': 'Apri la scheda quando il mirino giallo resta fermo su un oggetto.',
    'ui.apri-questo-punto-in-google-maps': 'Apri questo punto in Google Maps',
    'ui.astri': 'Astri',
    'ui.astri-dietro-i-monti': 'Astri dietro i monti',
    'ui.astrocalendario-di-ben': 'AstroCalendario di Ben',
    'ui.atlante-costellazioni': 'Atlante costellazioni',
    'ui.atlante-delle-costellazioni': 'Atlante delle costellazioni',
    'ui.atmosfera': 'Atmosfera',
    'ui.aurora': 'Aurora',
    'ui.avanti': 'Avanti',
    'ui.avanti-di-un-passo': 'Avanti di un passo',
    'ui.avvia-il-filmato-dell-ombra': 'Avvia il filmato dell\'ombra',
    'ui.avvia-il-playback': 'Avvia il playback',
    'ui.avvisami': 'Avvisami',
    'ui.avvisami-prima-di-un-evento': 'Avvisami prima di un evento',
    'ui.azzera': 'Azzera',
    'ui.backup-e-ripristino': 'Backup e ripristino',
    'ui.basta-la-citta-piu-vicina-per-gli-orari-del': 'Basta la città più vicina: per gli orari del cielo qualche chilometro non cambia nulla.',
    'ui.butta-questo-e-registra-di-nuovo': 'Butta questo e registra di nuovo',
    'ui.calcola-gli-eventi': 'Calcola gli eventi',
    'ui.calcolo-in-corso': 'Calcolo in corso…',
    'ui.calibra': 'Calibra',
    'ui.cambia-oculare': 'Cambia oculare:',
    'ui.campo-55': 'Campo 55°',
    'ui.caricamento-dei-dati-orbitali': 'Caricamento dei dati orbitali…',
    'ui.caricamento-del-planetario': 'Caricamento del planetario',
    'ui.carta-geografica-della-rotta-dellaereo': 'Carta geografica della rotta dell’aereo',
    'ui.categoria': 'Categoria',
    'ui.centra': 'Centra',
    'ui.cerca-il-luogo-per-nome': 'Cerca il luogo per nome',
    'ui.cerca-nel-sistema-solare': 'Cerca nel Sistema Solare',
    'ui.cerca-per-nome': 'Cerca per nome…',
    'ui.cerca-un-aereo': 'Cerca un aereo',
    'ui.cerca-un-astro-per-nome': 'Cerca un astro per nome',
    'ui.cerca-un-elemento-nel-sistema-solare': 'Cerca un elemento nel Sistema Solare',
    'ui.cerca-una-citta': 'Cerca una città',
    'ui.cerca-una-citta-o-un-paese': 'Cerca una città o un paese',
    'ui.cerca-una-costellazione': 'Cerca una costellazione',
    'ui.che-cielo-avrai': 'Che cielo avrai',
    'ui.che-cos-e-l-eclittica': 'Che cos\'è l\'eclittica',
    'ui.che-cosa-cercare': 'Che cosa cercare',
    'ui.che-cosa-regolare': 'Che cosa regolare',
    'ui.che-mappa-mostrare': 'Che mappa mostrare',
    'ui.chi-muove-la-vista': 'Chi muove la vista',
    'ui.chiede-al-dispositivo-la-posizione-attuale-e': 'Chiede al dispositivo la posizione attuale e porta qui il punto',
    'ui.chiede-il-permesso-al-browser-all-aperto-e': 'Chiede il permesso al browser. All\'aperto è la strada migliore.',
    'ui.chiedi-adesso-una-nuova-fotografia-senza': 'Chiedi adesso una nuova fotografia, senza aspettare il prossimo giro',
    'ui.chiudi': 'Chiudi',
    'ui.chiudi-i-comandi-del-tempo': 'Chiudi i comandi del tempo',
    'ui.chiudi-il-pannello-ads-b': 'Chiudi il pannello ADS-B',
    'ui.chiudi-l-avviso-del-transito': 'Chiudi l\'avviso del transito',
    'ui.chiudi-la-finestra': 'Chiudi la finestra',
    'ui.chiudi-la-finestra-o-premi-esc': 'Chiudi la finestra (o premi Esc)',
    'ui.chiudi-la-galleria': 'Chiudi la galleria',
    'ui.chiudi-la-mappa': 'Chiudi la mappa',
    'ui.chiudi-la-mappa-e-torna-al-planetario': 'Chiudi la mappa e torna al planetario',
    'ui.chiudi-la-scheda': 'Chiudi la scheda',
    'ui.chiudi-la-simulazione': 'Chiudi la simulazione',
    'ui.cielo': 'Cielo',
    'ui.cielo-limpido-vista-da-con-il-binocolo-ho': 'Cielo limpido, vista da... con il binocolo. Ho notato che...',
    'ui.circa-la-citta': 'circa la città',
    'ui.citta': 'Città',
    'ui.citta-e-montagne': 'Città e montagne',
    'ui.citta-e-montagne-trovate': 'Città e montagne trovate',
    'ui.citta-trovate': 'Città trovate',
    'ui.colore': 'Colore',
    'ui.com-e-andata': 'Com\'è andata?',
    'ui.comandi-del-planetario': 'Comandi del planetario',
    'ui.come-e-disegnato': 'Come è disegnato',
    'ui.come-guardare-il-cielo-e-cosa-disegnarci': 'Come guardare il cielo e cosa disegnarci: direzione, schermo, oggetti, aria, paesaggio',
    'ui.come-guardare-pieno-schermo-colori-notturni': 'Come guardare: pieno schermo, colori notturni, fotocamera, reticolo',
    'ui.come-guardarla-senza-farsi-male': 'Come guardarla senza farsi male',
    'ui.come-si-legge-la-mappa': 'Come si legge la mappa',
    'ui.come-si-leggono-i-colori': 'Come si leggono i colori',
    'ui.come-si-presenta-davvero-non-come-nelle': 'Come si presenta davvero, non come nelle fotografie',
    'ui.come-vederlo': 'Come vederlo',
    'ui.comete-e-asteroidi': 'Comete e asteroidi',
    'ui.comete-e-asteroidi-abbastanza-luminosi-da': 'Comete e asteroidi abbastanza luminosi da vedersi stanotte: quasi sempre non ce n\'è nessuno, e quando c\'è è il motivo per uscire',
    'ui.compresse': 'Compresse',
    'ui.compresse-per-farceli-stare-tutti-gli-angoli': 'Compresse per farceli stare tutti: gli angoli restano veri, i rapporti fra le distanze no',
    'ui.computer-doppio-clic-sul-terreno-telefono-un': 'Computer: doppio clic sul terreno · telefono: un tocco · poi scegli «Vai qua» · due dita per ingrandire · il segno azzurro è dove sei davvero',
    'ui.con-bussola-e-giroscopio-accesi-il-cielo-lo': 'Con bussola e giroscopio accesi il cielo lo punta il telefono. Spegnendolo la mappa la muovi tu col dito, e i tasti Centra e i punti cardinali tornano a funzionare',
    'ui.con-cosa-guardi': 'Con cosa guardi:',
    'ui.con-il-binocolo': 'Con il binocolo',
    'ui.con-il-telescopio': 'Con il telescopio',
    'ui.con-la-fotocamera': 'Con la fotocamera',
    'ui.condividi': 'Condividi',
    'ui.confronta-terreno-e-strade-attorno-a-te-e': 'Confronta terreno e strade attorno a te e cerca un punto pubblico, carrabile e con l\'evento libero sopra montagne e colline.',
    'ui.congela-il-tempo-sull-istante-mostrato': 'Congela il tempo sull\'istante mostrato',
    'ui.conosco-le-coordinate-esatte': 'Conosco le coordinate esatte',
    'ui.conserva-il-centro-e-l-elevazione-scelti': 'Conserva il centro e l\'elevazione scelti; ruota la camera e adatta soltanto lo zoom',
    'ui.controllo-del-tempo': 'Controllo del tempo',
    'ui.corpi-ingranditi-pallini-leggibili-e-comodi': 'Corpi ingranditi: pallini leggibili e comodi da toccare col dito. Nel banco Terra e Luna ingrandisce anche le ombre, così la geometria resta quella di due corpi tre volte più grandi.',
    'ui.cosa-aspettarsi': 'Cosa aspettarsi',
    'ui.cosa-disegnare-sulla-mappa-pianeti-stelle': 'Cosa disegnare sulla mappa: pianeti, stelle, satelliti, aerei',
    'ui.cosa-guardare': 'Cosa guardare',
    'ui.cosa-hai-davanti': 'Cosa hai davanti',
    'ui.cosa-portare': 'Cosa portare',
    'ui.cosa-si-vede-stanotte-da-casa-tua': 'Cosa si vede stanotte da casa tua',
    'ui.cosa-succede': 'Cosa succede',
    'ui.cosa-succede-nel-cielo-all-istante-che-stai': 'Cosa succede nel cielo all\'istante che stai guardando: eclissi, sciami meteorici, fasi lunari, congiunzioni',
    'ui.cosa-succede-nel-cielo-intorno-all-ora': 'Cosa succede nel cielo intorno all\'ora mostrata, e il programma dei sette giorni dopo. Spostando l\'orologio l\'elenco cambia con lui.',
    'ui.cosa-vedrai-minuto-per-minuto': 'Cosa vedrai, minuto per minuto',
    'ui.costellazioni': 'Costellazioni',
    'ui.da-0-5-a-10-secondi-il-conto-riparte-se-il': 'Da 0,5 a 10 secondi. Il conto riparte se il mirino lascia l’oggetto.',
    'ui.da-dove-guardare-il-cielo': 'Da dove guardare il cielo',
    'ui.da-dove-guardi': 'Da dove guardi',
    'ui.da-google-maps': 'Da Google Maps',
    'ui.da-qui': 'Da qui',
    'ui.da-qui-la-terra-in-basso-e-il-sole-davanti-a': 'Da qui: la Terra in basso e il Sole davanti a lei, cioè la disposizione di stasera vista da sopra casa nostra. A sinistra i pianeti della sera, a destra quelli del mattino.',
    'ui.da-qui-nell-istante-di-massima-eclissi-la': 'Da qui, nell\'istante di massima eclissi, la Luna è sopra l\'orizzonte.',
    'ui.dal': 'Dal',
    'ui.dalla-connessione': 'Dalla connessione',
    'ui.data-e-ora': 'Data e ora *',
    'ui.data-ora-e-playback-del-cielo': 'Data, ora e playback del cielo',
    'ui.dati': 'Dati',
    'ui.diario': 'Diario',
    'ui.diario-di-osservazione': 'Diario di osservazione',
    'ui.didat-tica': 'Didat­tica',
    'ui.dimensioni': 'Dimensioni',
    'ui.direzione': 'Direzione',
    'ui.direzione-della-vista': 'Direzione della vista',
    'ui.disegna-i-triangoli-sopra-il-cielo-colorati': 'Disegna i triangoli sopra il cielo, colorati per distanza. Non tocca il feed: spegnendolo i dati continuano ad arrivare',
    'ui.disegna-in-cielo-gli-aerei-ads-b-entro-il': 'Disegna in cielo gli aerei ADS-B entro il raggio scelto, colorati per distanza',
    'ui.disegni': 'Disegni',
    'ui.distanze': 'Distanze',
    'ui.distanze-e-dimensioni-compresse-per-farci': 'Distanze e dimensioni: compresse per farci stare tutto, o quelle vere',
    'ui.distanze-vere-nettuno-e-settantasette-volte': 'Distanze vere: Nettuno è settantasette volte più lontano di Mercurio, e si vede',
    'ui.dove-si-guarda-punti-cardinali-campo-visivo': 'Dove si guarda: punti cardinali, campo visivo, bussola e posizione',
    'ui.dove-sta-passando-l-ombra': 'Dove sta passando l\'ombra',
    'ui.dove-ti-trovi': 'Dove ti trovi',
    'ui.dove-vedere-l-evento': 'Dove vedere l\'evento',
    'ui.dove-vederlo': 'Dove vederlo',
    'ui.durata-della-registrazione': 'Durata della registrazione',
    'ui.e-la-posizione-principale-quella-che-comanda': 'È la posizione principale, quella che comanda tutta l\'app. Se la scegli tu, resta: GPS e rete non la sostituiscono da soli finché non chiedi un nuovo rilevamento. Nel planetario puoi spostare il punto di vista altrove senza toccare questa.',
    'ui.eclissi-lunare': 'Eclissi lunare',
    'ui.eclittica': 'Eclittica',
    'ui.esci': '✕ Esci',
    'ui.esci-dal-sistema-solare-e-guardalo-da-fuori': 'Esci dal Sistema Solare e guardalo da fuori: dove sta ogni pianeta sulla sua orbita in questo istante, e in che direzione lo stai guardando da qui. Si gira col dito.',
    'ui.esci-dallo-schermo-intero-anche-con-esc-o-un': 'Esci dallo schermo intero (anche con Esc o un doppio clic)',
    'ui.esporta-backup': 'Esporta backup',
    'ui.eventi': 'Eventi',
    'ui.eventi-in-cielo': 'Eventi in cielo',
    'ui.eventi-personali-diario-di-osservazione-e': 'Eventi personali, diario di osservazione e preferenze vivono solo in questo browser: salvali per non perderli.',
    'ui.fai-camminare-il-cielo-da-solo': 'Fai camminare il cielo da solo',
    'ui.fai-camminare-il-tempo': 'Fai camminare il tempo',
    'ui.fai-scorrere-il-cielo-all-indietro-ripremi': 'Fai scorrere il cielo all\'indietro (ripremi per fermarlo)',
    'ui.fai-scorrere-il-cielo-in-avanti-ripremi-per': 'Fai scorrere il cielo in avanti (ripremi per fermarlo)',
    'ui.ferma-il-filmato': 'Ferma il filmato',
    'ui.ferma-il-filmato-dell-ombra': 'Ferma il filmato dell\'ombra',
    'ui.ferma-il-playback': 'Ferma il playback',
    'ui.ferma-il-tempo': 'Ferma il tempo',
    'ui.ferma-la-simulazione': 'Ferma la simulazione',
    'ui.filtro-rosso-protegge-la-vista-notturna': 'Filtro rosso: protegge la vista notturna',
    'ui.fine': 'Fine',
    'ui.fotocamera': 'Fotocamera',
    'ui.galleria': 'Galleria',
    'ui.galleria-video': 'Galleria video',
    'ui.gestisci-la-posizione': 'Gestisci la posizione',
    'ui.giorno-del-mese': 'Giorno del mese',
    'ui.gira-la-vista-dove-succede': 'Gira la vista dove succede',
    'ui.gli-istanti-sono-gli-stessi-per-tutto-il': 'Gli istanti sono gli stessi per tutto il pianeta: cambia\n              solo se da dove sei la Luna, in quel momento, è sopra l\'orizzonte.',
    'ui.gli-oggetti-di-stanotte': 'Gli oggetti di stanotte',
    'ui.gli-orari-da-casa-tua': 'Gli orari, da casa tua',
    'ui.gps-del-dispositivo': 'GPS del dispositivo',
    'ui.gradi-decimali-con-il-punto-sud-e-ovest-si': 'Gradi decimali, con il punto: sud e ovest si scrivono col meno (−). Su una mappa online basta tenere premuto sul punto per leggerle.',
    'ui.guarda': 'Guarda',
    'ui.guarda-il-cielo-da-qui': 'Guarda il cielo da qui',
    'ui.guarda-verso': 'Guarda verso',
    'ui.guarda-verso-est': 'Guarda verso est',
    'ui.guarda-verso-nord': 'Guarda verso nord',
    'ui.guarda-verso-ovest': 'Guarda verso ovest',
    'ui.guarda-verso-sud': 'Guarda verso sud',
    'ui.guardalo-da-sotto': 'Guardalo da sotto',
    'ui.ho-visto': 'Ho visto!',
    'ui.i-laghi-e-i-fiumi-veri-attorno-a-te': 'I laghi e i fiumi veri attorno a te, disegnati dove sono e alla distanza a cui sono: l\'acqua ferma riflette il cielo come uno specchio, e la Luna ci fa la sua strada di luce. Si vedono solo quelli che non restano dietro a una cresta. Si scaricano da OpenStreetMap una volta sola e poi restano anche senza rete; fin dove cercarli si decide nelle Impostazioni',
    'ui.i-nomi-delle-montagne-che-spuntano-sopra-l': 'I nomi delle montagne che spuntano sopra l\'orizzonte, con la loro quota, agganciati alla vetta vera da un filo: si nominano solo quelle che da qui si vedono davvero, non quelle nascoste dietro a una cresta più vicina. Nascono spenti; una volta accesi si scaricano una volta sola e la scelta si ricorda. Fin dove cercarle si decide nelle Impostazioni',
    'ui.i-quadri-della-lezione': 'I quadri della lezione',
    'ui.ics-aiuto': 'Scarica un file <code>.ics</code> con i prossimi eventi: il calendario del telefono penserà lui ai promemoria, anche ad app chiusa.',
    'ui.il-cerchio-che-il-sole-percorre-in-un-anno': 'Il cerchio che il Sole percorre in un anno fra le stelle: il piano dell\'orbita terrestre visto di taglio. I pianeti stanno sempre a pochi gradi da questa linea, e il filo a piombo misura quanti. Resta accesa qualunque oggetto si scelga, finché non la si spegne',
    'ui.il-cielo-a-tutto-schermo-con-i-comandi-in': 'Il cielo a tutto schermo, con i comandi in sovrimpressione',
    'ui.il-cielo-che-hai': 'Il cielo che hai',
    'ui.il-cielo-da-cui-osservi': 'Il cielo da cui osservi',
    'ui.il-cielo-di-stanotte-da-casa-tua': 'Il cielo di stanotte, da casa tua',
    'ui.il-cielo-mostrato-non-e-quello-di-adesso': 'Il cielo mostrato non è quello di adesso: tocca per tornare al tempo reale',
    'ui.il-cielo-occupa-tutto-lo-schermo-anche-con': 'Il cielo occupa tutto lo schermo (anche con un doppio clic sulla mappa)',
    'ui.il-nord-punta-storto-bussola-e-posizione': 'Il Nord punta storto? Bussola e posizione',
    'ui.il-palazzo-di-fronte-la-collina-gli-alberi': 'Il palazzo di fronte, la collina, gli alberi. Dichiara quanto sono alti in gradi (un pugno a braccio teso è circa 10°) e da lì in poi l\'app smette di proporti cose che da casa tua non vedrai mai. Zero vuol dire orizzonte libero.',
    'ui.il-percorso-del-cono-d-ombra-sulla-terra': 'Il percorso del cono d\'ombra sulla Terra',
    'ui.il-planetario-e-su-questo-istante': 'Il planetario è su questo istante.',
    'ui.il-planetario-punta-il-telefono-verso-il': 'Il planetario: punta il telefono verso il cielo e vedi cosa c\'è',
    'ui.il-punto-che-al-massimo-ha-la-luna': 'Il punto che al massimo ha la Luna esattamente sopra la testa: da lì si guarda in alto, senza ostacoli.',
    'ui.il-resto-dell-app-dice-cosa-c-e-stanotte-qui': 'Il resto dell\'app dice cosa c\'è stanotte. Qui c\'è come inquadrarlo:\n          i conti sono fatti sul tuo strumento, le istruzioni parlano di manopole vere, e le due fasi difficili —\n          mettere l\'asse a Nord e trovare l\'oggetto — le fai guidato, con livella, bussola e push-to del telefono.',
    'ui.il-sistema-solare-a-tutto-schermo-con-la': 'Il Sistema Solare a tutto schermo, con la barra del tempo in sovrimpressione',
    'ui.il-sistema-solare-adesso': 'Il Sistema Solare, adesso',
    'ui.il-sistema-solare-in-3d': 'Il Sistema Solare in 3D',
    'ui.il-sistema-solare-visto-da-fuori-nello': 'Il Sistema Solare visto da fuori, nello stesso istante: si apre a tutto schermo, puntato sulla Terra',
    'ui.il-tempo': 'Il tempo',
    'ui.il-tuo-momento': 'Il tuo momento',
    'ui.il-tuo-sistema-solare': 'Il tuo Sistema Solare',
    'ui.il-tuo-telescopio': 'Il tuo telescopio',
    'ui.il-valore-predefinito-e-5-secondi-puoi': 'Il valore predefinito è 5 secondi; puoi scegliere da 1 a 60 secondi.',
    'ui.imposta-la-tua-posizione': 'Imposta la tua posizione',
    'ui.impostazioni': 'Impostazioni',
    'ui.in-attesa-dei-dati-ads-b': 'In attesa dei dati ADS-B…',
    'ui.incolla': 'Incolla',
    'ui.incolla-qui-il-link-di-google-maps-o-le': 'Incolla qui il link di Google Maps, o le coordinate',
    'ui.incolla-un-link-di-google-maps-o-scrivi-le': 'Incolla un link di Google Maps, o scrivi le coordinate',
    'ui.indietro': 'Indietro',
    'ui.indietro-di-un-passo': 'Indietro di un passo',
    'ui.informazioni-dal-mirino': 'Informazioni dal mirino',
    'ui.ingrandisci-fino-a-vedere-i-mari-della-luna': 'Ingrandisci (fino a vedere i mari della Luna e gli anelli di Saturno)',
    'ui.ingrandite': 'Ingrandite',
    'ui.inizio': 'Inizio',
    'ui.insegui': 'Insegui',
    'ui.installa-l-app': 'Installa l\'app',
    'ui.installa-l-app-sul-dispositivo': 'Installa l\'app sul dispositivo',
    'ui.istante-mostrato-apri-i-comandi-del-tempo': 'Istante mostrato: apri i comandi del tempo',
    'ui.kp-vero': 'Kp vero',
    'ui.l-aria-sopra-di-te-colore-del-cielo-nuvole': 'L\'aria sopra di te: colore del cielo, nuvole, aurora',
    'ui.l-ho-vista-scrivilo-nel-diario': 'L\'ho vista: scrivilo nel diario',
    'ui.l-istante-mostrato-tocca-per-data-passo-e': 'L\'istante mostrato: tocca per data, passo e velocità del playback',
    'ui.l-istante-mostrato-tocca-per-scrivere-una': 'L\'istante mostrato: tocca per scrivere una data',
    'ui.l-orizzonte-attorno-a-te': 'L\'orizzonte attorno a te',
    'ui.l-orizzonte-prende-la-forma-vera-del-terreno': 'L\'orizzonte prende la forma vera del terreno attorno a te: colline, montagne, mare, pianura — ognuno col suo colore. Si scarica una volta sola e poi resta anche senza rete. Spento, il terreno non viene disegnato. Ingrandendo molto su un astro il terreno diventa trasparente da sé, come in Stellarium',
    'ui.la-citta-in-elenco-o-le-coordinate-esatte': 'La città in elenco o le coordinate esatte. Funziona anche offline e senza permessi.',
    'ui.la-classifica-usa-le-strade-e-i-divieti-di': 'La classifica usa le strade e i divieti di accesso presenti in OpenStreetMap, oltre a quota e profilo del terreno. I dati possono essere incompleti: prima di partire verifica segnaletica, possibilità di fermarti, meteo e sicurezza del luogo.',
    'ui.la-forma-vera-del-terreno-non-solo-la-sua': 'La forma vera del terreno, non solo la sua sagoma: le valli che scendono, i fianchi delle colline, il solco del fiume, disegnati a tratti come su una tavola panoramica. Attorno a te il passo è di ventisette metri, contro i tre gradi del profilo a bande. Si scarica una volta sola per luogo (da quattro a sei tessere) e poi resta anche senza rete. Spento, torna il profilo a bande',
    'ui.la-luna-entra-nell-ombra-della-terra-chi-la': 'La Luna entra nell\'ombra della Terra: chi la vede in cielo la vede tutta, nello stesso istante',
    'ui.la-mappa-a-tutto-schermo-con-i-comandi-in': 'La mappa a tutto schermo, con i comandi in sovrimpressione',
    'ui.la-mappa-non-e-disponibile-adesso-serve-la': 'La mappa non è disponibile adesso — serve la rete per caricarla.\n              Le coordinate del pannello «Da Google Maps» funzionano lo stesso.',
    'ui.la-modalita-hover-e-disponibile-quando-la': 'La modalità hover è disponibile quando la vista segue il telefono',
    'ui.la-posizione-resta-salvata-solo-su-questo': 'La posizione resta salvata solo su questo dispositivo: non viene inviata a nessuno, e l\'app la usa per fare i conti in locale.',
    'ui.la-scegli-tu': 'La scegli tu',
    'ui.la-strada-che-l-oggetto-scelto-percorre-nel': 'La strada che l\'oggetto scelto percorre nel cielo nelle ore attorno a questo istante: tratteggiata dove è già passato, piena dove sta andando, con l\'ora segnata di ora in ora',
    'ui.la-terra-e-la-luna-da-vicino-coi-due-coni-d': 'La Terra e la Luna da vicino, coi due coni d\'ombra: è qui che si vede perché un\'eclissi non capita a ogni Luna piena — l\'orbita della Luna è inclinata di 5,1°, e a quella distanza sono trentaquattromila chilometri fuori bersaglio.',
    'ui.la-terra-sotto-di-te-terreno-rilievo-luci': 'La terra sotto di te: terreno, rilievo, luci, acque',
    'ui.la-tua-nota': 'La tua nota',
    'ui.la-tua-posizione': 'La tua posizione',
    'ui.laboratorio': 'Laboratorio',
    'ui.laboratorio-didattico-e-simulazioni': 'Laboratorio didattico e simulazioni interattive della meccanica celeste',
    'ui.laghi-e-fiumi': 'Laghi e fiumi',
    'ui.lascia-solo-gli-astri-che-adesso-stanno': 'Lascia solo gli astri che adesso stanno sopra l\'orizzonte',
    'ui.latitudine': 'Latitudine',
    'ui.le-cupole-di-luce-dei-paesi-veri-attorno-a': 'Le cupole di luce dei paesi veri attorno a te, col loro nome sull\'orizzonte: dicono da che parte NON cercare le cose deboli. Di giorno non si vedono',
    'ui.le-distanze-fra-le-orbite-sono-compresse-per': 'Le distanze fra le orbite sono compresse per farcele stare tutte nello\n          schermo: Saturno è davvero venticinque volte più lontano di Mercurio. Gli angoli, che sono\n          quello di cui parla la lezione, sono invece quelli veri.',
    'ui.le-eclissi-di-casa-tua': 'Le eclissi di casa tua',
    'ui.le-figure-delle-costellazioni': 'Le figure delle costellazioni',
    'ui.le-ottantotto-costellazioni-la-figura-il': 'Le ottantotto costellazioni: la figura, il disegno, i nomi che le hanno dato le altre culture, e da qui si vede o no. Metà sono australi e dall\'Italia non sorgono mai: da lì si può andare.',
    'ui.le-registrazioni-salvate-con-astrocalendario': 'Le registrazioni salvate con AstroCalendario, disponibili anche senza rete',
    'ui.le-stelle-luminose-di-riferimento': 'Le stelle luminose di riferimento',
    'ui.le-tue-osservazioni': 'Le tue osservazioni',
    'ui.le-tue-osservazioni-e-i-traguardi-raggiunti': 'Le tue osservazioni e i traguardi raggiunti',
    'ui.lenta': 'lenta',
    'ui.linea-del-giorno-e-della-notte': 'Linea del giorno e della notte',
    'ui.lo-zoom-con-due-dita-rotellina-o-trackpad': 'Lo zoom con due dita, rotellina o trackpad resta sempre disponibile.',
    'ui.longitudine': 'Longitudine',
    'ui.luci-delle-citta': 'Luci delle città',
    'ui.luna-allo-zenit': 'Luna allo zenit',
    'ui.luogo-incolla-aiuto': 'In Google Maps tieni premuto sul punto: compaiono le coordinate, e si copiano con un tocco. Vanno bene anche i link lunghi con <code>@</code>, i gradi e primi (45°58\'34"N 7°39\'29"E) e i due numeri secchi. I link corti <code>maps.app.goo.gl</code> no: aprili una volta, e copia quello che diventano.',
    'ui.mandalo-con-le-app-del-telefono': 'Mandalo con le app del telefono',
    'ui.mappa': 'Mappa',
    'ui.mappa-a-tutto-schermo': 'Mappa a tutto schermo',
    'ui.mappa-a-tutto-schermo-o-premi-f': 'Mappa a tutto schermo (o premi F)',
    'ui.mappa-dei-punti-di-osservazione': 'Mappa dei punti di osservazione',
    'ui.mappa-di-visibilita': 'Mappa di visibilità',
    'ui.mappa-sul-computer-fai-doppio-clic-sul': 'Mappa: sul computer fai doppio clic; sul telefono tocca un punto, poi scegli Vai qua',
    'ui.marcia': 'Marcia',
    'ui.massimo': 'Massimo',
    'ui.mese': 'Mese',
    'ui.mese-corrente': 'Mese corrente',
    'ui.metti-in-pausa-il-tempo': 'Metti in pausa il tempo',
    'ui.mini-mappa-di-vai-qua': 'Mini-mappa di “Vai qua”',
    'ui.minuto-per-minuto': 'Minuto per minuto',
    'ui.misure-vere-i-diametri-seguono-la-scala': 'Misure vere: i diametri seguono la scala astronomica dello zoom; con Distanze reali tutto usa lo stesso metro. Nel banco Terra e Luna anche le ombre sono esatte',
    'ui.modalita-hover': 'Modalità hover',
    'ui.modalita-notte': 'Modalità notte',
    'ui.mostra': 'Mostra',
    'ui.mostra-anche-cio-che-in-questo-momento-e': 'Mostra anche ciò che in questo momento è sotto l\'orizzonte',
    'ui.mostra-gli-astri-anche-quando-si-trovano': 'Mostra gli astri anche quando si trovano dietro il profilo di colline e montagne. Spento, il terreno li nasconde come avviene nella realtà',
    'ui.mostra-i-pulsanti-e-sulla-mappa': 'Mostra i pulsanti + e − sulla mappa',
    'ui.mostra-il-colore-del-cielo-la-foschia-e-gli': 'Mostra il colore del cielo, la foschia e gli aloni. Spegnendola si spengono anche le nuvole',
    'ui.mostra-in-cielo': 'Mostra in cielo',
    'ui.mostra-tutti-i-dati': 'Mostra tutti i dati',
    'ui.nasconde-tutte-le-informazioni-e-i-comandi': 'Nasconde tutte le informazioni e i comandi in sovrimpressione; resta solo il pulsante di registrazione. Tocca il cielo per farli ricomparire',
    'ui.nascondi-automaticamente-la-carta-del': 'Nascondi automaticamente la carta del tragitto dopo questo tempo.',
    'ui.nascondi-la-linea-del-giorno-e-della-notte': 'Nascondi la linea del giorno e della notte',
    'ui.nel-planetario-puoi-vedere-paesi-acqua': 'Nel planetario puoi vedere paesi, acqua, montagne e aerei in tempo reale. Fin dove cercarli lo decidi qui, sulla carta: al centro c\'è dove guardi il cielo, e i quattro cerchi sono i raggi di ricerca. Trascina il bordo di un cerchio, oppure tocca il punto fin dove vuoi arrivare; puoi anche allargare la mappa a tutto schermo.',
    'ui.nel-raggio': 'nel raggio',
    'ui.nessun-astro-con-questo-nome': 'Nessun astro con questo nome.',
    'ui.nomi-astri': 'Nomi astri',
    'ui.nomi-dei-monti': 'Nomi dei monti',
    'ui.non-impostata': 'Non impostata.',
    'ui.normale': 'normale',
    'ui.nuovo-evento': 'Nuovo evento',
    'ui.nuvole': 'Nuvole',
    'ui.oggetti': 'Oggetti',
    'ui.ogni-riga-e-un-eclissi-solare-che-da-questo': 'Ogni riga e\' un\'eclissi solare che da questo punto si vede,\n          almeno in parte. Toccane una per aprirne la mappa.',
    'ui.oppure-un-intervallo': 'Oppure un intervallo',
    'ui.orari-calcolati-per-il-punto-che-hai-scelto': 'Orari calcolati per il punto che hai scelto.\n            Tocca una riga per portare lì il cursore del tempo.',
    'ui.orizzonte-libero': 'Orizzonte libero',
    'ui.osservazione': 'Osservazione',
    'ui.paesaggio': 'Paesaggio',
    'ui.passa-al-fondo-scuro-di-notte-con-gli-occhi': 'Passa al fondo scuro: di notte, con gli occhi abituati al buio, una mappa chiara abbaglia',
    'ui.passo': 'Passo',
    'ui.pausa': 'Pausa',
    'ui.perche-il-cielo-fa-quello-che-fa': 'Perché il cielo fa quello che fa',
    'ui.perche-l-ombra-disegna-una-curva-a-s': 'Perché l\'ombra disegna una curva a S',
    'ui.perche-proprio-adesso-la-stagione-delle': 'Perché proprio adesso: la stagione delle eclissi',
    'ui.permette-di-correggere-la-bussola': 'Permette di correggere la bussola trascinando il dito sul cielo',
    'ui.pianeti': 'Pianeti',
    'ui.plane-tario': 'Plane­tario',
    'ui.planetario': 'Planetario',
    'ui.porta-al-centro-della-mappa-l-oggetto': 'Porta al centro della mappa l\'oggetto selezionato',
    'ui.porta-gli-eventi-nel-tuo-calendario': 'Porta gli eventi nel tuo calendario',
    'ui.porta-il-cielo-alla-data-scritta-qui-accanto': 'Porta il cielo alla data scritta qui accanto (o premi Invio)',
    'ui.porta-il-punto-qui': 'Porta il punto qui',
    'ui.posizione': 'Posizione',
    'ui.posizione-attuale': 'Posizione attuale',
    'ui.posizioni-ads-b-entro-il-raggio-scelto-50-km': 'Posizioni ADS-B entro il raggio scelto (50 km di serie; si cambia nelle Impostazioni). Il colore dice quanto è vicino; la linea tratteggiata è la rotta dei 5 minuti successivi. Spostando l\'orologio, aereo e rotta diventano stime coerenti con l\'istante mostrato.',
    'ui.precisa-al-metro': 'precisa al metro',
    'ui.prendi-quello-che-hai-copiato': 'Prendi quello che hai copiato',
    'ui.prepariamo-il-planetario': 'Prepariamo il planetario',
    'ui.programma-facoltativo': 'Programma (facoltativo)',
    'ui.prossimi-appuntamenti': 'Prossimi appuntamenti',
    'ui.pulisci': 'Pulisci',
    'ui.punta-il-mirino-su-un-astro-che-vedi-davvero': 'Punta il mirino su un astro che vedi davvero (la Luna, il Sole, un pianeta, una stella luminosa) e tocca qui: la bussola si corregge sul cielo vero',
    'ui.quando': 'Quando',
    'ui.quante-stelle-si-vedono-non-dipende-dal': 'Quante stelle si vedono non dipende dal cielo ma da dove lo guardi. Scegli quello che assomiglia di più al tuo: comanda il planetario (quante stelle disegna), la scelta dei bersagli di stanotte e il conto del contrasto al telescopio.',
    'ui.quanti-minuti-di-eclissi-scorrono-in-un': 'Quanti minuti di eclissi scorrono in un secondo di filmato',
    'ui.quanto-manca-alla-forma-vera-del-terreno': 'Quanto manca alla forma vera del terreno',
    'ui.quanto-tempo-del-cielo-passa-in-un-secondo': 'Quanto tempo del cielo passa in un secondo vero',
    'ui.quanto-tempo-passa-in-un-secondo-vero': 'Quanto tempo passa in un secondo vero',
    'ui.qui-la-luna-resta-su-dal-primo-all-ultimo': 'Qui la Luna resta su dal primo all\'ultimo contatto. La zona è più stretta perché intanto la Terra gira.',
    'ui.raggio-di-ricerca': 'Raggio di ricerca',
    'ui.rallenta-il-playback': 'Rallenta il playback',
    'ui.rallenta-il-tempo': 'Rallenta il tempo',
    'ui.rapidissima': 'rapidissima',
    'ui.reali': 'Reali',
    'ui.registra-il-cielo': 'Registra il cielo',
    'ui.registra-il-sistema-solare-3d': 'Registra il Sistema Solare 3D',
    'ui.registra-qualche-secondo-del-sistema-solare': 'Registra qualche secondo del Sistema Solare 3D da condividere',
    'ui.registrala-nel-diario-delle-tue-osservazioni': 'Registrala nel diario delle tue osservazioni',
    'ui.registrazione-del-cielo': 'Registrazione del cielo',
    'ui.reticolo': 'Reticolo',
    'ui.rifai': 'Rifai',
    'ui.rileva-di-nuovo-la-posizione-gps-poi-rete': 'Rileva di nuovo la posizione: GPS, poi rete, poi a mano',
    'ui.rilievo': 'Rilievo',
    'ui.rimetti-in-vista-il-punto-scelto': 'Rimetti in vista il punto scelto',
    'ui.rimetti-la-vista-com-era-all-apertura-stessa': 'Rimetti la vista com\'era all\'apertura: stessa inquadratura, stesso ingrandimento (o premi R)',
    'ui.rimetti-la-vista-come-all-apertura': 'Rimetti la vista come all\'apertura',
    'ui.rimuovi': 'Rimuovi',
    'ui.rinfresca-la-fotografia-da-solo-quando': 'Rinfresca la fotografia da solo quando invecchia: ogni 45 secondi col disegno acceso, ogni tre minuti quando i dati stanno solo in memoria',
    'ui.ripristina-backup': 'Ripristina backup',
    'ui.riproduci': 'Riproduci',
    'ui.rotta-dellaereo': 'Rotta dell’aereo',
    'ui.ruota-la-bussola-verso-est': 'Ruota la bussola verso est',
    'ui.ruota-la-bussola-verso-ovest': 'Ruota la bussola verso ovest',
    'ui.salva': 'Salva',
    'ui.salva-evento': 'Salva evento',
    'ui.salva-le-mappe-per-l-uso-offline': 'Salva le mappe per l\'uso offline',
    'ui.salva-nel-diario': 'Salva nel diario',
    'ui.satellite': 'Satellite',
    'ui.satelliti': 'Satelliti',
    'ui.scarica-i-prossimi-12-mesi': 'Scarica i prossimi 12 mesi',
    'ui.scarica-il-file-sul-dispositivo': 'Scarica il file sul dispositivo',
    'ui.scarica-le-tessere-della-mappa-attorno-a': 'Scarica le tessere della mappa attorno a questo punto: il giorno dell\'eclissi potresti non avere rete',
    'ui.scegli-cartella': 'Scegli cartella',
    'ui.scegli-il-luogo-da-cui-stai-osservando': 'Scegli il luogo da cui stai osservando',
    'ui.scegli-la-durata-dei-video-creati-dal-tasto': 'Scegli la durata dei video creati dal tasto rosso del planetario.',
    'ui.scegli-sulla-mappa-il-punto-da-cui-guardare': 'Scegli sulla mappa il punto da cui guardare il cielo',
    'ui.scegli-tu-il-luogo': 'Scegli tu il luogo',
    'ui.scegli-un-punto-sulla-mappa-per-vedere-cosa': 'Scegli un punto sulla mappa per vedere cosa succede lì.',
    'ui.schermo': 'Schermo',
    'ui.schermo-intero': 'Schermo intero',
    'ui.scorri-il-tempo': 'Scorri il tempo',
    'ui.scorri-il-tempo-dentro-la-finestra-scelta': 'Scorri il tempo dentro la finestra scelta',
    'ui.scrivi-le-prime-lettere-l-elenco-si-stringe': 'Scrivi le prime lettere: l\'elenco si stringe. Invio sceglie il primo.',
    'ui.se-il-gps-non-risponde-nessun-permesso-ma': 'Se il GPS non risponde: nessun permesso, ma può sbagliare di decine di chilometri.',
    'ui.secondi': 'secondi',
    'ui.segna-sulla-mappa-gli-eventi-in-corso-all': 'Segna sulla mappa gli eventi in corso all\'ora mostrata: il radiante di uno sciame, l\'astro eclissato, i corpi di una congiunzione',
    'ui.segna-visto-su-un-evento-dell-agenda-e': 'Segna “Visto!” su un evento dell\'agenda e finisce qui, con la tua nota.',
    'ui.segni-e-aiuti': 'Segni e aiuti',
    'ui.segui-il-telefono': 'Segui il telefono',
    'ui.segui-l-ombra': 'Segui l\'ombra',
    'ui.sei-banchi-di-prova-con-dentro-le-posizioni': 'Sei banchi di prova con dentro le posizioni vere dei pianeti, per capire le sei cose che stanno\n          dietro a tutto il resto dell\'app: perché i pianeti a volte tornano indietro, quali sono le tre\n          regole che comandano ogni orbita, come si guadagna velocità passando vicino a un pianeta, perché\n          per Marte si parte solo ogni ventisei mesi, quando i pianeti si mettono davvero in fila e come\n          fa il Sole ad accendere un\'aurora dall\'altra parte del pianeta.\n          Ogni banco finisce con i tasti che portano la stessa cosa nel planetario e nel Sistema Solare in 3D.',
    'ui.sempre-disponibile': 'sempre disponibile',
    'ui.serve-per-gli-orari-di-sorgere-e-tramonto-il': 'Serve per gli orari di sorgere e tramonto, il buio astronomico, il meteo e i passaggi della ISS',
    'ui.serve-per-orari-di-sorgere-e-tramonto-buio': 'Serve per orari di sorgere e tramonto, buio astronomico, meteo e passaggi delle stazioni spaziali. Si può rilevare col GPS, dedurre dalla connessione oppure scegliere a mano.',
    'ui.sezioni-delle-impostazioni': 'Sezioni delle impostazioni',
    'ui.siamo-un-modo-per-il-cosmo-di-conoscere-se': '«Siamo un modo per il cosmo di conoscere se stesso.»',
    'ui.sicurezza': 'Sicurezza',
    'ui.simula-una-tempesta': 'Simula una tempesta',
    'ui.simulazione': 'Simulazione',
    'ui.sistema-solare-3d': 'Sistema Solare 3D',
    'ui.sole-coperto': 'Sole coperto',
    'ui.sole-e-luna': 'Sole e Luna',
    'ui.sopra-le-linee-la-figura-il-cacciatore-il': 'Sopra le linee, la figura: il cacciatore, il leone, la nave. È un velo leggero, appoggiato sulle stelle vere — a campo largo si accenna appena, ingrandendo molto sparisce da sé. Tocca una figura sulla mappa per aprire la sua pagina',
    'ui.sotto-l-orizzonte': 'Sotto l\'orizzonte',
    'ui.sovrapponi-il-cielo-all-immagine-della': 'Sovrapponi il cielo all\'immagine della fotocamera: il campo visivo diventa quello dell\'obiettivo, e il pizzico lo tara',
    'ui.spostamento-geografico-della-vista-apri-la': 'Spostamento geografico della vista. Apri la mappa interattiva a tutto schermo',
    'ui.stanotte': 'Stanotte',
    'ui.stasera': 'Stasera',
    'ui.stazioni-spaziali': 'Stazioni spaziali',
    'ui.stelle': 'Stelle',
    'ui.sto-preparando-il-cielo-5-044-stelle-in': 'Sto preparando il cielo: 5.044 stelle in arrivo…',
    'ui.stop': 'Stop',
    'ui.strumento-usato': 'Strumento usato',
    'ui.su-ora': 'Su ora',
    'ui.tara-su-un-astro': 'Tara su un astro',
    'ui.tele-scopio': 'Tele­scopio',
    'ui.tempo': 'Tempo',
    'ui.terra-e-luna': 'Terra e Luna',
    'ui.terreno-vero': 'Terreno vero',
    'ui.tiene-la-mappa-centrata-sull-ombra-mentre': 'Tiene la mappa centrata sull\'ombra mentre corre',
    'ui.tiene-vivo-il-feed-ads-b-spegnendolo-si': 'Tiene vivo il feed ADS-B. Spegnendolo si fermano le richieste e la fotografia viene buttata',
    'ui.tieni-al-centro-l-oggetto-scelto-la-vista-lo': 'Tieni al centro l\'oggetto scelto: la vista lo segue da sola',
    'ui.tieni-l-oggetto-selezionato-sempre-al-centro': 'Tieni l\'oggetto selezionato sempre al centro della mappa: la vista lo segue mentre il cielo ruota o mentre scorre il playback',
    'ui.tienila-visibile-fino-al-prossimo-punto': 'Tienila visibile fino al prossimo punto premuto nel planetario',
    'ui.titolo': 'Titolo *',
    'ui.tocca-per-esplorare': 'Tocca per esplorare',
    'ui.tocca-un-punto-qualunque-del-mappamondo-per': 'Tocca un punto qualunque del mappamondo per sceglierlo, oppure toccalo due volte per andarci subito: il planetario disegnerà il cielo di lì. La posizione dell\'app non si tocca.',
    'ui.tocca-una-citta-per-portare-li-il-tuo-punto': 'Tocca una città per portare lì il tuo punto di osservazione.',
    'ui.toccane-uno-la-mappa-lo-porta-al-centro-e': 'Toccane uno: la mappa lo porta al centro e una freccia ti guida. Per la scheda dei dati, toccalo sulla mappa.',
    'ui.togli-lintervallo': 'Togli l’intervallo',
    'ui.torna-al-campo-visivo-di-partenza-55-con-la': 'Torna al campo visivo di partenza, 55° (con la fotocamera accesa: azzera la taratura dell\'obiettivo)',
    'ui.torna-al-kp-misurato-dal-noaa-per-quest-ora': 'Torna al Kp misurato dal NOAA per quest\'ora',
    'ui.torna-al-planetario': 'Torna al planetario',
    'ui.torna-alla-bussola-del-telefono-senza': 'Torna alla bussola del telefono, senza correzioni',
    'ui.traccia': 'Traccia',
    'ui.trascina-per-girare-tocca-un-pianeta-doppio': 'Trascina per girare · tocca un pianeta · doppio tocco sulla Terra per impostare il punto giallo',
    'ui.trascina-per-scorrere-il-tempo': 'Trascina per scorrere il tempo',
    'ui.trascina-per-scorrere-il-tempo-dentro-la': 'Trascina per scorrere il tempo dentro la finestra scelta',
    'ui.trascina-per-spostarti-nel-tempo': 'Trascina per spostarti nel tempo',
    'ui.trova-il-punto-migliore': 'Trova il punto migliore',
    'ui.trova-la-mia-posizione': 'Trova la mia posizione',
    'ui.tutte-e-ottantotto-la-figura-il-disegno-i': 'Tutte e ottantotto: la figura, il disegno, i nomi delle altre culture',
    'ui.tutte-le-costellazioni': '← Tutte le costellazioni',
    'ui.tutte-le-eclissi-solari-visibili-da-questo': 'Tutte le eclissi solari visibili da questo punto, fino al 2070',
    'ui.tutte-le-eclissi-solari-visibili-dalla-tua': 'Tutte le eclissi solari visibili dalla tua posizione',
    'ui.tutte-le-eclissi-visibili-da-qui': 'Tutte le eclissi visibili da qui',
    'ui.tutti-i-dati-di-questo-oggetto': 'Tutti i dati di questo oggetto',
    'ui.tutti-i-prossimi': 'Tutti i prossimi',
    'ui.tutto': 'Tutto',
    'ui.tutto-il-sistema-fino-a-nettuno-e-alla': 'Tutto il sistema, fino a Nettuno e alla fascia di Kuiper',
    'ui.usa-queste-coordinate': 'Usa queste coordinate',
    'ui.vai': 'Vai',
    'ui.vai-al-mese': 'Vai al mese',
    'ui.vale-solo-per-il-planetario-orari-meteo': 'Vale solo per il planetario: orari, meteo, passaggi delle stazioni spaziali e telescopio restano sulla tua posizione, quella delle Impostazioni.',
    'ui.vede-il-momento-del-massimo': 'Vede il momento del massimo',
    'ui.vede-l-eclissi-per-intero': 'Vede l\'eclissi per intero',
    'ui.veloce': 'veloce',
    'ui.velocita': 'Velocità',
    'ui.velocita-del-tempo': 'Velocità del tempo',
    'ui.velocita-della-simulazione': 'Velocità della simulazione',
    'ui.vista-pulita': 'Vista pulita',
    'ui.visualizzazione': 'Visualizzazione',
    'ui.zenit': 'Zenit',
  }
};
